/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.ReciboRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recibo extends TableImpl<ReciboRecord> {

    private static final long serialVersionUID = -1641787547;

    /**
     * The reference instance of <code>MG.RECIBO</code>
     */
    public static final Recibo RECIBO = new Recibo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReciboRecord> getRecordType() {
        return ReciboRecord.class;
    }

    /**
     * The column <code>MG.RECIBO.ID</code>.
     */
    public final TableField<ReciboRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.RECIBO.FECHAHORA</code>.
     */
    public final TableField<ReciboRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.RECIBO.NOMBRE</code>.
     */
    public final TableField<ReciboRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

    /**
     * The column <code>MG.RECIBO.CONCEPTO</code>.
     */
    public final TableField<ReciboRecord, String> CONCEPTO = createField("CONCEPTO", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>MG.RECIBO.MONTO</code>.
     */
    public final TableField<ReciboRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.RECIBO</code> table reference
     */
    public Recibo() {
        this("RECIBO", null);
    }

    /**
     * Create an aliased <code>MG.RECIBO</code> table reference
     */
    public Recibo(String alias) {
        this(alias, RECIBO);
    }

    private Recibo(String alias, Table<ReciboRecord> aliased) {
        this(alias, aliased, null);
    }

    private Recibo(String alias, Table<ReciboRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Recibo as(String alias) {
        return new Recibo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Recibo rename(String name) {
        return new Recibo(name, null);
    }
}
