/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblAportesImporteMensualSaldoAnteriorRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAportesImporteMensualSaldoAnterior extends TableImpl<TblAportesImporteMensualSaldoAnteriorRecord> {

    private static final long serialVersionUID = -80715113;

    /**
     * The reference instance of <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR</code>
     */
    public static final TblAportesImporteMensualSaldoAnterior TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR = new TblAportesImporteMensualSaldoAnterior();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblAportesImporteMensualSaldoAnteriorRecord> getRecordType() {
        return TblAportesImporteMensualSaldoAnteriorRecord.class;
    }

    /**
     * The column <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID</code>.
     */
    public final TableField<TblAportesImporteMensualSaldoAnteriorRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID_ENTIDAD</code>.
     */
    public final TableField<TblAportesImporteMensualSaldoAnteriorRecord, Integer> ID_ENTIDAD = createField("ID_ENTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ANO</code>.
     */
    public final TableField<TblAportesImporteMensualSaldoAnteriorRecord, Integer> ANO = createField("ANO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.IMPORTE_MESNUAL</code>.
     */
    public final TableField<TblAportesImporteMensualSaldoAnteriorRecord, Long> IMPORTE_MESNUAL = createField("IMPORTE_MESNUAL", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.SALDO_ANTERIOR</code>.
     */
    public final TableField<TblAportesImporteMensualSaldoAnteriorRecord, Long> SALDO_ANTERIOR = createField("SALDO_ANTERIOR", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR</code> table reference
     */
    public TblAportesImporteMensualSaldoAnterior() {
        this("TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR", null);
    }

    /**
     * Create an aliased <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR</code> table reference
     */
    public TblAportesImporteMensualSaldoAnterior(String alias) {
        this(alias, TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR);
    }

    private TblAportesImporteMensualSaldoAnterior(String alias, Table<TblAportesImporteMensualSaldoAnteriorRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblAportesImporteMensualSaldoAnterior(String alias, Table<TblAportesImporteMensualSaldoAnteriorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblAportesImporteMensualSaldoAnteriorRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblAportesImporteMensualSaldoAnteriorRecord> getPrimaryKey() {
        return Keys.SQL170227183746700;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblAportesImporteMensualSaldoAnteriorRecord>> getKeys() {
        return Arrays.<UniqueKey<TblAportesImporteMensualSaldoAnteriorRecord>>asList(Keys.SQL170227183746700);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblAportesImporteMensualSaldoAnteriorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblAportesImporteMensualSaldoAnteriorRecord, ?>>asList(Keys.SQL170227183746720);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnterior as(String alias) {
        return new TblAportesImporteMensualSaldoAnterior(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblAportesImporteMensualSaldoAnterior rename(String name) {
        return new TblAportesImporteMensualSaldoAnterior(name, null);
    }
}
