/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblAutofacturasAsientosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAutofacturasAsientos extends TableImpl<TblAutofacturasAsientosRecord> {

    private static final long serialVersionUID = 539559260;

    /**
     * The reference instance of <code>MG.TBL_AUTOFACTURAS_ASIENTOS</code>
     */
    public static final TblAutofacturasAsientos TBL_AUTOFACTURAS_ASIENTOS = new TblAutofacturasAsientos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblAutofacturasAsientosRecord> getRecordType() {
        return TblAutofacturasAsientosRecord.class;
    }

    /**
     * The column <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_AUTOFACTURA</code>.
     */
    public final TableField<TblAutofacturasAsientosRecord, Integer> ID_AUTOFACTURA = createField("ID_AUTOFACTURA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_ASIENTO</code>.
     */
    public final TableField<TblAutofacturasAsientosRecord, Integer> ID_ASIENTO = createField("ID_ASIENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_AUTOFACTURAS_ASIENTOS</code> table reference
     */
    public TblAutofacturasAsientos() {
        this("TBL_AUTOFACTURAS_ASIENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_AUTOFACTURAS_ASIENTOS</code> table reference
     */
    public TblAutofacturasAsientos(String alias) {
        this(alias, TBL_AUTOFACTURAS_ASIENTOS);
    }

    private TblAutofacturasAsientos(String alias, Table<TblAutofacturasAsientosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblAutofacturasAsientos(String alias, Table<TblAutofacturasAsientosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblAutofacturasAsientosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblAutofacturasAsientosRecord, ?>>asList(Keys.SQL160414103608830, Keys.SQL160414103608960);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasAsientos as(String alias) {
        return new TblAutofacturasAsientos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblAutofacturasAsientos rename(String name) {
        return new TblAutofacturasAsientos(name, null);
    }
}
