/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblAsientosTemporalesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAsientosTemporales extends TableImpl<TblAsientosTemporalesRecord> {

    private static final long serialVersionUID = 1284046489;

    /**
     * The reference instance of <code>MG.TBL_ASIENTOS_TEMPORALES</code>
     */
    public static final TblAsientosTemporales TBL_ASIENTOS_TEMPORALES = new TblAsientosTemporales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblAsientosTemporalesRecord> getRecordType() {
        return TblAsientosTemporalesRecord.class;
    }

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ID</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.FECHAHORA</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_DEBE</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> ID_CUENTA_CONTABLE_DEBE = createField("ID_CUENTA_CONTABLE_DEBE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_HABER</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> ID_CUENTA_CONTABLE_HABER = createField("ID_CUENTA_CONTABLE_HABER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.MONTO</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ES_APORTE</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Boolean> ES_APORTE = createField("ES_APORTE", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.FACTURADO</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Boolean> FACTURADO = createField("FACTURADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("FALSE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_DEBE</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> ID_CENTRO_DE_COSTO_DEBE = createField("ID_CENTRO_DE_COSTO_DEBE", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_HABER</code>.
     */
    public final TableField<TblAsientosTemporalesRecord, Integer> ID_CENTRO_DE_COSTO_HABER = createField("ID_CENTRO_DE_COSTO_HABER", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>MG.TBL_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblAsientosTemporales() {
        this("TBL_ASIENTOS_TEMPORALES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblAsientosTemporales(String alias) {
        this(alias, TBL_ASIENTOS_TEMPORALES);
    }

    private TblAsientosTemporales(String alias, Table<TblAsientosTemporalesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblAsientosTemporales(String alias, Table<TblAsientosTemporalesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblAsientosTemporalesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_ASIENTOS_TEMPORALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblAsientosTemporalesRecord> getPrimaryKey() {
        return Keys.SQL160414103607050;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblAsientosTemporalesRecord>> getKeys() {
        return Arrays.<UniqueKey<TblAsientosTemporalesRecord>>asList(Keys.SQL160414103607050);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblAsientosTemporalesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblAsientosTemporalesRecord, ?>>asList(Keys.SQL160414103611480, Keys.SQL160414103611590, Keys.SQL160906141910580, Keys.SQL160906141910800);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporales as(String alias) {
        return new TblAsientosTemporales(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblAsientosTemporales rename(String name) {
        return new TblAsientosTemporales(name, null);
    }
}
