/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblAutofacturasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAutofacturas extends TableImpl<TblAutofacturasRecord> {

    private static final long serialVersionUID = 1699853328;

    /**
     * The reference instance of <code>MG.TBL_AUTOFACTURAS</code>
     */
    public static final TblAutofacturas TBL_AUTOFACTURAS = new TblAutofacturas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblAutofacturasRecord> getRecordType() {
        return TblAutofacturasRecord.class;
    }

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.ID</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.NRO</code>.
     */
    public final TableField<TblAutofacturasRecord, String> NRO = createField("NRO", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.ID_TIMBRADO</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> ID_TIMBRADO = createField("ID_TIMBRADO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.FECHAHORA</code>.
     */
    public final TableField<TblAutofacturasRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.NOMBRE</code>.
     */
    public final TableField<TblAutofacturasRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.DOMICILIO</code>.
     */
    public final TableField<TblAutofacturasRecord, String> DOMICILIO = createField("DOMICILIO", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.DIRECCION_DE_TRANSACCION</code>.
     */
    public final TableField<TblAutofacturasRecord, String> DIRECCION_DE_TRANSACCION = createField("DIRECCION_DE_TRANSACCION", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.CI</code>.
     */
    public final TableField<TblAutofacturasRecord, String> CI = createField("CI", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.CANTIDAD</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> CANTIDAD = createField("CANTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.CONCEPTO</code>.
     */
    public final TableField<TblAutofacturasRecord, String> CONCEPTO = createField("CONCEPTO", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.PRECIO_UNITARIO</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> PRECIO_UNITARIO = createField("PRECIO_UNITARIO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.MONTO</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.OBSERVACION</code>.
     */
    public final TableField<TblAutofacturasRecord, String> OBSERVACION = createField("OBSERVACION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.ANULADO</code>.
     */
    public final TableField<TblAutofacturasRecord, Boolean> ANULADO = createField("ANULADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("FALSE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.ID_USER</code>.
     */
    public final TableField<TblAutofacturasRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_AUTOFACTURAS.CONDICION_CONTADO</code>.
     */
    public final TableField<TblAutofacturasRecord, Boolean> CONDICION_CONTADO = createField("CONDICION_CONTADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("TRUE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>MG.TBL_AUTOFACTURAS</code> table reference
     */
    public TblAutofacturas() {
        this("TBL_AUTOFACTURAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_AUTOFACTURAS</code> table reference
     */
    public TblAutofacturas(String alias) {
        this(alias, TBL_AUTOFACTURAS);
    }

    private TblAutofacturas(String alias, Table<TblAutofacturasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblAutofacturas(String alias, Table<TblAutofacturasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblAutofacturasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_AUTOFACTURAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblAutofacturasRecord> getPrimaryKey() {
        return Keys.SQL160414103604920;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblAutofacturasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblAutofacturasRecord>>asList(Keys.SQL160414103604920);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblAutofacturasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblAutofacturasRecord, ?>>asList(Keys.SQL160414103614030, Keys.SQL160414103613650);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturas as(String alias) {
        return new TblAutofacturas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblAutofacturas rename(String name) {
        return new TblAutofacturas(name, null);
    }
}
