/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblCuentasContablesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCuentasContables extends TableImpl<TblCuentasContablesRecord> {

    private static final long serialVersionUID = -1073415011;

    /**
     * The reference instance of <code>MG.TBL_CUENTAS_CONTABLES</code>
     */
    public static final TblCuentasContables TBL_CUENTAS_CONTABLES = new TblCuentasContables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblCuentasContablesRecord> getRecordType() {
        return TblCuentasContablesRecord.class;
    }

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES.ID</code>.
     */
    public final TableField<TblCuentasContablesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES.DESCRIPCION</code>.
     */
    public final TableField<TblCuentasContablesRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES.ID_CUENTA_MADRE</code>.
     */
    public final TableField<TblCuentasContablesRecord, Integer> ID_CUENTA_MADRE = createField("ID_CUENTA_MADRE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES.IMPUTABLE</code>.
     */
    public final TableField<TblCuentasContablesRecord, Boolean> IMPUTABLE = createField("IMPUTABLE", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>MG.TBL_CUENTAS_CONTABLES</code> table reference
     */
    public TblCuentasContables() {
        this("TBL_CUENTAS_CONTABLES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_CUENTAS_CONTABLES</code> table reference
     */
    public TblCuentasContables(String alias) {
        this(alias, TBL_CUENTAS_CONTABLES);
    }

    private TblCuentasContables(String alias, Table<TblCuentasContablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblCuentasContables(String alias, Table<TblCuentasContablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblCuentasContablesRecord> getPrimaryKey() {
        return Keys.SQL160414103605690;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblCuentasContablesRecord>> getKeys() {
        return Arrays.<UniqueKey<TblCuentasContablesRecord>>asList(Keys.SQL160414103605690);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblCuentasContablesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblCuentasContablesRecord, ?>>asList(Keys.SQL160414103611720);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContables as(String alias) {
        return new TblCuentasContables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblCuentasContables rename(String name) {
        return new TblCuentasContables(name, null);
    }
}
