/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblCuentasContablesPorDefectoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCuentasContablesPorDefecto extends TableImpl<TblCuentasContablesPorDefectoRecord> {

    private static final long serialVersionUID = 1590517122;

    /**
     * The reference instance of <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO</code>
     */
    public static final TblCuentasContablesPorDefecto TBL_CUENTAS_CONTABLES_POR_DEFECTO = new TblCuentasContablesPorDefecto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblCuentasContablesPorDefectoRecord> getRecordType() {
        return TblCuentasContablesPorDefectoRecord.class;
    }

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO = createField("ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("101010200", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO = createField("ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("201010100", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DEBE_COMPRAS</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_DEBE_COMPRAS = createField("ID_CUENTA_DEBE_COMPRAS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("501010900", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_A_COBRAR</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_A_COBRAR = createField("ID_CUENTA_A_COBRAR", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("101020100", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_APORTES</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_APORTES = createField("ID_CUENTA_APORTES", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("401010100", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DONACIONES</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_DONACIONES = createField("ID_CUENTA_DONACIONES", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("401010200", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CAJA</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_CAJA = createField("ID_CUENTA_CAJA", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("101010100", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CTA_CTE</code>.
     */
    public final TableField<TblCuentasContablesPorDefectoRecord, Integer> ID_CUENTA_CTA_CTE = createField("ID_CUENTA_CTA_CTE", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("101010200", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO</code> table reference
     */
    public TblCuentasContablesPorDefecto() {
        this("TBL_CUENTAS_CONTABLES_POR_DEFECTO", null);
    }

    /**
     * Create an aliased <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO</code> table reference
     */
    public TblCuentasContablesPorDefecto(String alias) {
        this(alias, TBL_CUENTAS_CONTABLES_POR_DEFECTO);
    }

    private TblCuentasContablesPorDefecto(String alias, Table<TblCuentasContablesPorDefectoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblCuentasContablesPorDefecto(String alias, Table<TblCuentasContablesPorDefectoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblCuentasContablesPorDefectoRecord> getPrimaryKey() {
        return Keys.SQL160414103606070;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblCuentasContablesPorDefectoRecord>> getKeys() {
        return Arrays.<UniqueKey<TblCuentasContablesPorDefectoRecord>>asList(Keys.SQL160414103606070);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblCuentasContablesPorDefectoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblCuentasContablesPorDefectoRecord, ?>>asList(Keys.SQL160414103611910, Keys.SQL160414103612060, Keys.SQL160414103612230, Keys.SQL160414103612380, Keys.SQL160414103612560, Keys.SQL160414103612740, Keys.SQL160414103612880, Keys.SQL160414103613070);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefecto as(String alias) {
        return new TblCuentasContablesPorDefecto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblCuentasContablesPorDefecto rename(String name) {
        return new TblCuentasContablesPorDefecto(name, null);
    }
}
