/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblEntidadesHistoricoCategoriasRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEntidadesHistoricoCategorias extends TableImpl<TblEntidadesHistoricoCategoriasRecord> {

    private static final long serialVersionUID = 364906964;

    /**
     * The reference instance of <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS</code>
     */
    public static final TblEntidadesHistoricoCategorias TBL_ENTIDADES_HISTORICO_CATEGORIAS = new TblEntidadesHistoricoCategorias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEntidadesHistoricoCategoriasRecord> getRecordType() {
        return TblEntidadesHistoricoCategoriasRecord.class;
    }

    /**
     * The column <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID</code>.
     */
    public final TableField<TblEntidadesHistoricoCategoriasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_ENTIDAD</code>.
     */
    public final TableField<TblEntidadesHistoricoCategoriasRecord, Integer> ID_ENTIDAD = createField("ID_ENTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ANO_MES</code>.
     */
    public final TableField<TblEntidadesHistoricoCategoriasRecord, Integer> ANO_MES = createField("ANO_MES", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_CATEGORIA_DE_PAGO</code>.
     */
    public final TableField<TblEntidadesHistoricoCategoriasRecord, Integer> ID_CATEGORIA_DE_PAGO = createField("ID_CATEGORIA_DE_PAGO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS</code> table reference
     */
    public TblEntidadesHistoricoCategorias() {
        this("TBL_ENTIDADES_HISTORICO_CATEGORIAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS</code> table reference
     */
    public TblEntidadesHistoricoCategorias(String alias) {
        this(alias, TBL_ENTIDADES_HISTORICO_CATEGORIAS);
    }

    private TblEntidadesHistoricoCategorias(String alias, Table<TblEntidadesHistoricoCategoriasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEntidadesHistoricoCategorias(String alias, Table<TblEntidadesHistoricoCategoriasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblEntidadesHistoricoCategoriasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_ENTIDADES_HISTORICO_CATEGORIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEntidadesHistoricoCategoriasRecord> getPrimaryKey() {
        return Keys.SQL170227183746070;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEntidadesHistoricoCategoriasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEntidadesHistoricoCategoriasRecord>>asList(Keys.SQL170227183746070);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblEntidadesHistoricoCategoriasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblEntidadesHistoricoCategoriasRecord, ?>>asList(Keys.SQL170227183746190, Keys.SQL170227183746270);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategorias as(String alias) {
        return new TblEntidadesHistoricoCategorias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblEntidadesHistoricoCategorias rename(String name) {
        return new TblEntidadesHistoricoCategorias(name, null);
    }
}
