/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblEventoCuotasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventoCuotas extends TableImpl<TblEventoCuotasRecord> {

    private static final long serialVersionUID = -167646548;

    /**
     * The reference instance of <code>MG.TBL_EVENTO_CUOTAS</code>
     */
    public static final TblEventoCuotas TBL_EVENTO_CUOTAS = new TblEventoCuotas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEventoCuotasRecord> getRecordType() {
        return TblEventoCuotasRecord.class;
    }

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.ID_EVENTO</code>.
     */
    public final TableField<TblEventoCuotasRecord, Integer> ID_EVENTO = createField("ID_EVENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.FECHA_1</code>.
     */
    public final TableField<TblEventoCuotasRecord, Timestamp> FECHA_1 = createField("FECHA_1", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.FECHA_2</code>.
     */
    public final TableField<TblEventoCuotasRecord, Timestamp> FECHA_2 = createField("FECHA_2", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.FECHA_3</code>.
     */
    public final TableField<TblEventoCuotasRecord, Timestamp> FECHA_3 = createField("FECHA_3", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.FECHA_4</code>.
     */
    public final TableField<TblEventoCuotasRecord, Timestamp> FECHA_4 = createField("FECHA_4", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_EVENTO_CUOTAS.ID_USER</code>.
     */
    public final TableField<TblEventoCuotasRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_EVENTO_CUOTAS</code> table reference
     */
    public TblEventoCuotas() {
        this("TBL_EVENTO_CUOTAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_EVENTO_CUOTAS</code> table reference
     */
    public TblEventoCuotas(String alias) {
        this(alias, TBL_EVENTO_CUOTAS);
    }

    private TblEventoCuotas(String alias, Table<TblEventoCuotasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEventoCuotas(String alias, Table<TblEventoCuotasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEventoCuotasRecord> getPrimaryKey() {
        return Keys.SQL160209153451390;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEventoCuotasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEventoCuotasRecord>>asList(Keys.SQL160209153451390);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblEventoCuotasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblEventoCuotasRecord, ?>>asList(Keys.SQL160209153458250);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotas as(String alias) {
        return new TblEventoCuotas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblEventoCuotas rename(String name) {
        return new TblEventoCuotas(name, null);
    }
}
