/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblEventoDetalleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventoDetalle extends TableImpl<TblEventoDetalleRecord> {

    private static final long serialVersionUID = 473972957;

    /**
     * The reference instance of <code>MG.TBL_EVENTO_DETALLE</code>
     */
    public static final TblEventoDetalle TBL_EVENTO_DETALLE = new TblEventoDetalle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEventoDetalleRecord> getRecordType() {
        return TblEventoDetalleRecord.class;
    }

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.FECHAHORA</code>.
     */
    public final TableField<TblEventoDetalleRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.OBSERVACION</code>.
     */
    public final TableField<TblEventoDetalleRecord, String> OBSERVACION = createField("OBSERVACION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.MONTO</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID_ENTIDAD</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID_ENTIDAD = createField("ID_ENTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID_EVENTO</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID_EVENTO = createField("ID_EVENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID_CATEGORIA_ARTICULO</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID_CATEGORIA_ARTICULO = createField("ID_CATEGORIA_ARTICULO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID_FORMA_DE_PAGO_PREFERIDA</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID_FORMA_DE_PAGO_PREFERIDA = createField("ID_FORMA_DE_PAGO_PREFERIDA", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_EVENTO_DETALLE.ID_USER</code>.
     */
    public final TableField<TblEventoDetalleRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_EVENTO_DETALLE</code> table reference
     */
    public TblEventoDetalle() {
        this("TBL_EVENTO_DETALLE", null);
    }

    /**
     * Create an aliased <code>MG.TBL_EVENTO_DETALLE</code> table reference
     */
    public TblEventoDetalle(String alias) {
        this(alias, TBL_EVENTO_DETALLE);
    }

    private TblEventoDetalle(String alias, Table<TblEventoDetalleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEventoDetalle(String alias, Table<TblEventoDetalleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblEventoDetalleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_EVENTO_DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEventoDetalleRecord> getPrimaryKey() {
        return Keys.SQL160209153450770;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEventoDetalleRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEventoDetalleRecord>>asList(Keys.SQL160209153450770);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblEventoDetalleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblEventoDetalleRecord, ?>>asList(Keys.SQL160209153457750, Keys.SQL160209153457360, Keys.SQL160209153457570, Keys.SQL160209153457950, Keys.SQL160209153458090);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalle as(String alias) {
        return new TblEventoDetalle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblEventoDetalle rename(String name) {
        return new TblEventoDetalle(name, null);
    }
}
