/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblEventosRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventos extends TableImpl<TblEventosRecord> {

    private static final long serialVersionUID = -91558743;

    /**
     * The reference instance of <code>MG.TBL_EVENTOS</code>
     */
    public static final TblEventos TBL_EVENTOS = new TblEventos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEventosRecord> getRecordType() {
        return TblEventosRecord.class;
    }

    /**
     * The column <code>MG.TBL_EVENTOS.ID</code>.
     */
    public final TableField<TblEventosRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.FECHA</code>.
     */
    public final TableField<TblEventosRecord, Timestamp> FECHA = createField("FECHA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.DESCRIPCION</code>.
     */
    public final TableField<TblEventosRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.PORCENTAJE_APORTE</code>.
     */
    public final TableField<TblEventosRecord, Integer> PORCENTAJE_APORTE = createField("PORCENTAJE_APORTE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.ID_EVENTO_TIPO</code>.
     */
    public final TableField<TblEventosRecord, Integer> ID_EVENTO_TIPO = createField("ID_EVENTO_TIPO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.ID_USER</code>.
     */
    public final TableField<TblEventosRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.ID_GRUPO</code>.
     */
    public final TableField<TblEventosRecord, Integer> ID_GRUPO = createField("ID_GRUPO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_EVENTOS.ID_CENTRO_DE_COSTO</code>.
     */
    public final TableField<TblEventosRecord, Integer> ID_CENTRO_DE_COSTO = createField("ID_CENTRO_DE_COSTO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_EVENTOS</code> table reference
     */
    public TblEventos() {
        this("TBL_EVENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_EVENTOS</code> table reference
     */
    public TblEventos(String alias) {
        this(alias, TBL_EVENTOS);
    }

    private TblEventos(String alias, Table<TblEventosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEventos(String alias, Table<TblEventosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblEventosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_EVENTOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEventosRecord> getPrimaryKey() {
        return Keys.SQL160209153450100;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEventosRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEventosRecord>>asList(Keys.SQL160209153450100);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblEventosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblEventosRecord, ?>>asList(Keys.SQL160209153456600, Keys.SQL160209153457190, Keys.SQL160209153456900, Keys.SQL160414103607800);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventos as(String alias) {
        return new TblEventos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblEventos rename(String name) {
        return new TblEventos(name, null);
    }
}
