/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblFacturasAsientosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblFacturasAsientos extends TableImpl<TblFacturasAsientosRecord> {

    private static final long serialVersionUID = 1320291697;

    /**
     * The reference instance of <code>MG.TBL_FACTURAS_ASIENTOS</code>
     */
    public static final TblFacturasAsientos TBL_FACTURAS_ASIENTOS = new TblFacturasAsientos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblFacturasAsientosRecord> getRecordType() {
        return TblFacturasAsientosRecord.class;
    }

    /**
     * The column <code>MG.TBL_FACTURAS_ASIENTOS.NRO_FACTURA</code>.
     */
    public final TableField<TblFacturasAsientosRecord, Integer> NRO_FACTURA = createField("NRO_FACTURA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS_ASIENTOS.ID_ASIENTO</code>.
     */
    public final TableField<TblFacturasAsientosRecord, Integer> ID_ASIENTO = createField("ID_ASIENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_FACTURAS_ASIENTOS</code> table reference
     */
    public TblFacturasAsientos() {
        this("TBL_FACTURAS_ASIENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_FACTURAS_ASIENTOS</code> table reference
     */
    public TblFacturasAsientos(String alias) {
        this(alias, TBL_FACTURAS_ASIENTOS);
    }

    private TblFacturasAsientos(String alias, Table<TblFacturasAsientosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblFacturasAsientos(String alias, Table<TblFacturasAsientosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblFacturasAsientosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblFacturasAsientosRecord, ?>>asList(Keys.SQL160414103609550, Keys.SQL160414103609720);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasAsientos as(String alias) {
        return new TblFacturasAsientos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblFacturasAsientos rename(String name) {
        return new TblFacturasAsientos(name, null);
    }
}
