/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblFacturasCompraAsientosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblFacturasCompraAsientos extends TableImpl<TblFacturasCompraAsientosRecord> {

    private static final long serialVersionUID = 1253574773;

    /**
     * The reference instance of <code>MG.TBL_FACTURAS_COMPRA_ASIENTOS</code>
     */
    public static final TblFacturasCompraAsientos TBL_FACTURAS_COMPRA_ASIENTOS = new TblFacturasCompraAsientos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblFacturasCompraAsientosRecord> getRecordType() {
        return TblFacturasCompraAsientosRecord.class;
    }

    /**
     * The column <code>MG.TBL_FACTURAS_COMPRA_ASIENTOS.ID_FACTURA_COMPRA</code>.
     */
    public final TableField<TblFacturasCompraAsientosRecord, Integer> ID_FACTURA_COMPRA = createField("ID_FACTURA_COMPRA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS_COMPRA_ASIENTOS.ID_ASIENTO</code>.
     */
    public final TableField<TblFacturasCompraAsientosRecord, Integer> ID_ASIENTO = createField("ID_ASIENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_FACTURAS_COMPRA_ASIENTOS</code> table reference
     */
    public TblFacturasCompraAsientos() {
        this("TBL_FACTURAS_COMPRA_ASIENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_FACTURAS_COMPRA_ASIENTOS</code> table reference
     */
    public TblFacturasCompraAsientos(String alias) {
        this(alias, TBL_FACTURAS_COMPRA_ASIENTOS);
    }

    private TblFacturasCompraAsientos(String alias, Table<TblFacturasCompraAsientosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblFacturasCompraAsientos(String alias, Table<TblFacturasCompraAsientosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblFacturasCompraAsientosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblFacturasCompraAsientosRecord, ?>>asList(Keys.SQL160414103608580, Keys.SQL160414103608740);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraAsientos as(String alias) {
        return new TblFacturasCompraAsientos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblFacturasCompraAsientos rename(String name) {
        return new TblFacturasCompraAsientos(name, null);
    }
}
