/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblFacturasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblFacturas extends TableImpl<TblFacturasRecord> {

    private static final long serialVersionUID = 2032661881;

    /**
     * The reference instance of <code>MG.TBL_FACTURAS</code>
     */
    public static final TblFacturas TBL_FACTURAS = new TblFacturas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblFacturasRecord> getRecordType() {
        return TblFacturasRecord.class;
    }

    /**
     * The column <code>MG.TBL_FACTURAS.NRO</code>.
     */
    public final TableField<TblFacturasRecord, Integer> NRO = createField("NRO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.ID_TIMBRADO</code>.
     */
    public final TableField<TblFacturasRecord, Integer> ID_TIMBRADO = createField("ID_TIMBRADO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.FECHAHORA</code>.
     */
    public final TableField<TblFacturasRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.ID_ENTIDAD</code>.
     */
    public final TableField<TblFacturasRecord, Integer> ID_ENTIDAD = createField("ID_ENTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.RAZON_SOCIAL</code>.
     */
    public final TableField<TblFacturasRecord, String> RAZON_SOCIAL = createField("RAZON_SOCIAL", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.RUC</code>.
     */
    public final TableField<TblFacturasRecord, String> RUC = createField("RUC", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.IMPORTE_DONACION</code>.
     */
    public final TableField<TblFacturasRecord, Integer> IMPORTE_DONACION = createField("IMPORTE_DONACION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.IMPORTE_APORTE</code>.
     */
    public final TableField<TblFacturasRecord, Integer> IMPORTE_APORTE = createField("IMPORTE_APORTE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.ANULADO</code>.
     */
    public final TableField<TblFacturasRecord, Boolean> ANULADO = createField("ANULADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("FALSE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.ID_USER</code>.
     */
    public final TableField<TblFacturasRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.DOMICILIO</code>.
     */
    public final TableField<TblFacturasRecord, String> DOMICILIO = createField("DOMICILIO", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>MG.TBL_FACTURAS.CASILLA_DE_CORREO</code>.
     */
    public final TableField<TblFacturasRecord, Integer> CASILLA_DE_CORREO = createField("CASILLA_DE_CORREO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_FACTURAS</code> table reference
     */
    public TblFacturas() {
        this("TBL_FACTURAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_FACTURAS</code> table reference
     */
    public TblFacturas(String alias) {
        this(alias, TBL_FACTURAS);
    }

    private TblFacturas(String alias, Table<TblFacturasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblFacturas(String alias, Table<TblFacturasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblFacturasRecord> getPrimaryKey() {
        return Keys.SQL160209153455990;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblFacturasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblFacturasRecord>>asList(Keys.SQL160209153455990);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblFacturasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblFacturasRecord, ?>>asList(Keys.SQL160209153501480, Keys.SQL160209153501300, Keys.SQL160209153501660);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturas as(String alias) {
        return new TblFacturas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblFacturas rename(String name) {
        return new TblFacturas(name, null);
    }
}
