/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblIglesiaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblIglesia extends TableImpl<TblIglesiaRecord> {

    private static final long serialVersionUID = 1584863050;

    /**
     * The reference instance of <code>MG.TBL_IGLESIA</code>
     */
    public static final TblIglesia TBL_IGLESIA = new TblIglesia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblIglesiaRecord> getRecordType() {
        return TblIglesiaRecord.class;
    }

    /**
     * The column <code>MG.TBL_IGLESIA.ID</code>.
     */
    public final TableField<TblIglesiaRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_IGLESIA.NOMBRE</code>.
     */
    public final TableField<TblIglesiaRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_IGLESIA.RUC_SIN_DV</code>.
     */
    public final TableField<TblIglesiaRecord, String> RUC_SIN_DV = createField("RUC_SIN_DV", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>MG.TBL_IGLESIA.CTACTE</code>.
     */
    public final TableField<TblIglesiaRecord, Integer> CTACTE = createField("CTACTE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_IGLESIA.DOMICILIO</code>.
     */
    public final TableField<TblIglesiaRecord, String> DOMICILIO = createField("DOMICILIO", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>MG.TBL_IGLESIA.BOX</code>.
     */
    public final TableField<TblIglesiaRecord, Integer> BOX = createField("BOX", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_IGLESIA</code> table reference
     */
    public TblIglesia() {
        this("TBL_IGLESIA", null);
    }

    /**
     * Create an aliased <code>MG.TBL_IGLESIA</code> table reference
     */
    public TblIglesia(String alias) {
        this(alias, TBL_IGLESIA);
    }

    private TblIglesia(String alias, Table<TblIglesiaRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblIglesia(String alias, Table<TblIglesiaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblIglesiaRecord> getPrimaryKey() {
        return Keys.SQL160209153451830;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblIglesiaRecord>> getKeys() {
        return Arrays.<UniqueKey<TblIglesiaRecord>>asList(Keys.SQL160209153451830);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesia as(String alias) {
        return new TblIglesia(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblIglesia rename(String name) {
        return new TblIglesia(name, null);
    }
}
