/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblMiembrosRelacionesRolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosRelacionesRoles extends TableImpl<TblMiembrosRelacionesRolesRecord> {

    private static final long serialVersionUID = 1990828297;

    /**
     * The reference instance of <code>MG.TBL_MIEMBROS_RELACIONES_ROLES</code>
     */
    public static final TblMiembrosRelacionesRoles TBL_MIEMBROS_RELACIONES_ROLES = new TblMiembrosRelacionesRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblMiembrosRelacionesRolesRecord> getRecordType() {
        return TblMiembrosRelacionesRolesRecord.class;
    }

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.ID</code>.
     */
    public final TableField<TblMiembrosRelacionesRolesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.DESCRIPCION</code>.
     */
    public final TableField<TblMiembrosRelacionesRolesRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_MIEMBROS_RELACIONES_ROLES</code> table reference
     */
    public TblMiembrosRelacionesRoles() {
        this("TBL_MIEMBROS_RELACIONES_ROLES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_MIEMBROS_RELACIONES_ROLES</code> table reference
     */
    public TblMiembrosRelacionesRoles(String alias) {
        this(alias, TBL_MIEMBROS_RELACIONES_ROLES);
    }

    private TblMiembrosRelacionesRoles(String alias, Table<TblMiembrosRelacionesRolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblMiembrosRelacionesRoles(String alias, Table<TblMiembrosRelacionesRolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblMiembrosRelacionesRolesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_MIEMBROS_RELACIONES_ROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblMiembrosRelacionesRolesRecord> getPrimaryKey() {
        return Keys.SQL160209153452440;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblMiembrosRelacionesRolesRecord>> getKeys() {
        return Arrays.<UniqueKey<TblMiembrosRelacionesRolesRecord>>asList(Keys.SQL160209153452440);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRoles as(String alias) {
        return new TblMiembrosRelacionesRoles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblMiembrosRelacionesRoles rename(String name) {
        return new TblMiembrosRelacionesRoles(name, null);
    }
}
