/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblMiembrosAlergiasRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosAlergias extends TableImpl<TblMiembrosAlergiasRecord> {

    private static final long serialVersionUID = -1056596929;

    /**
     * The reference instance of <code>MG.TBL_MIEMBROS_ALERGIAS</code>
     */
    public static final TblMiembrosAlergias TBL_MIEMBROS_ALERGIAS = new TblMiembrosAlergias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblMiembrosAlergiasRecord> getRecordType() {
        return TblMiembrosAlergiasRecord.class;
    }

    /**
     * The column <code>MG.TBL_MIEMBROS_ALERGIAS.ID</code>.
     */
    public final TableField<TblMiembrosAlergiasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_ALERGIAS.DESCRIPCION</code>.
     */
    public final TableField<TblMiembrosAlergiasRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_MIEMBROS_ALERGIAS</code> table reference
     */
    public TblMiembrosAlergias() {
        this("TBL_MIEMBROS_ALERGIAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_MIEMBROS_ALERGIAS</code> table reference
     */
    public TblMiembrosAlergias(String alias) {
        this(alias, TBL_MIEMBROS_ALERGIAS);
    }

    private TblMiembrosAlergias(String alias, Table<TblMiembrosAlergiasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblMiembrosAlergias(String alias, Table<TblMiembrosAlergiasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblMiembrosAlergiasRecord> getPrimaryKey() {
        return Keys.SQL160209153454000;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblMiembrosAlergiasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblMiembrosAlergiasRecord>>asList(Keys.SQL160209153454000);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosAlergias as(String alias) {
        return new TblMiembrosAlergias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblMiembrosAlergias rename(String name) {
        return new TblMiembrosAlergias(name, null);
    }
}
