/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblMiembrosRelacionesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosRelaciones extends TableImpl<TblMiembrosRelacionesRecord> {

    private static final long serialVersionUID = -1499080429;

    /**
     * The reference instance of <code>MG.TBL_MIEMBROS_RELACIONES</code>
     */
    public static final TblMiembrosRelaciones TBL_MIEMBROS_RELACIONES = new TblMiembrosRelaciones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblMiembrosRelacionesRecord> getRecordType() {
        return TblMiembrosRelacionesRecord.class;
    }

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_FAMILIA</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_MIEMBROS_FAMILIA = createField("ID_MIEMBROS_FAMILIA", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_1</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_ENTIDAD_1 = createField("ID_ENTIDAD_1", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_2</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_ENTIDAD_2 = createField("ID_ENTIDAD_2", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_TIPO</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_MIEMBROS_RELACIONES_TIPO = createField("ID_MIEMBROS_RELACIONES_TIPO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_1</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_MIEMBROS_RELACIONES_ROL_1 = createField("ID_MIEMBROS_RELACIONES_ROL_1", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_2</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_MIEMBROS_RELACIONES_ROL_2 = createField("ID_MIEMBROS_RELACIONES_ROL_2", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_INICIO</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Timestamp> FECHA_INICIO = createField("FECHA_INICIO", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_FIN</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Timestamp> FECHA_FIN = createField("FECHA_FIN", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_RELACIONES.ID_USER</code>.
     */
    public final TableField<TblMiembrosRelacionesRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>MG.TBL_MIEMBROS_RELACIONES</code> table reference
     */
    public TblMiembrosRelaciones() {
        this("TBL_MIEMBROS_RELACIONES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_MIEMBROS_RELACIONES</code> table reference
     */
    public TblMiembrosRelaciones(String alias) {
        this(alias, TBL_MIEMBROS_RELACIONES);
    }

    private TblMiembrosRelaciones(String alias, Table<TblMiembrosRelacionesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblMiembrosRelaciones(String alias, Table<TblMiembrosRelacionesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblMiembrosRelacionesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_MIEMBROS_RELACIONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblMiembrosRelacionesRecord> getPrimaryKey() {
        return Keys.SQL160209153452040;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblMiembrosRelacionesRecord>> getKeys() {
        return Arrays.<UniqueKey<TblMiembrosRelacionesRecord>>asList(Keys.SQL160209153452040);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblMiembrosRelacionesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblMiembrosRelacionesRecord, ?>>asList(Keys.SQL160209153458620, Keys.SQL160209153458280, Keys.SQL160209153458430, Keys.SQL160209153458780, Keys.SQL160209153459020, Keys.SQL160209153459160, Keys.SQL160209153459330);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelaciones as(String alias) {
        return new TblMiembrosRelaciones(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblMiembrosRelaciones rename(String name) {
        return new TblMiembrosRelaciones(name, null);
    }
}
