/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblMiembrosFamiliasRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosFamilias extends TableImpl<TblMiembrosFamiliasRecord> {

    private static final long serialVersionUID = 1656527966;

    /**
     * The reference instance of <code>MG.TBL_MIEMBROS_FAMILIAS</code>
     */
    public static final TblMiembrosFamilias TBL_MIEMBROS_FAMILIAS = new TblMiembrosFamilias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblMiembrosFamiliasRecord> getRecordType() {
        return TblMiembrosFamiliasRecord.class;
    }

    /**
     * The column <code>MG.TBL_MIEMBROS_FAMILIAS.ID</code>.
     */
    public final TableField<TblMiembrosFamiliasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_FAMILIAS.DESCRIPCION</code>.
     */
    public final TableField<TblMiembrosFamiliasRecord, String> DESCRIPCION = createField("DESCRIPCION", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>MG.TBL_MIEMBROS_FAMILIAS.FOTO</code>.
     */
    public final TableField<TblMiembrosFamiliasRecord, byte[]> FOTO = createField("FOTO", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>MG.TBL_MIEMBROS_FAMILIAS</code> table reference
     */
    public TblMiembrosFamilias() {
        this("TBL_MIEMBROS_FAMILIAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_MIEMBROS_FAMILIAS</code> table reference
     */
    public TblMiembrosFamilias(String alias) {
        this(alias, TBL_MIEMBROS_FAMILIAS);
    }

    private TblMiembrosFamilias(String alias, Table<TblMiembrosFamiliasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblMiembrosFamilias(String alias, Table<TblMiembrosFamiliasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblMiembrosFamiliasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_MIEMBROS_FAMILIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblMiembrosFamiliasRecord> getPrimaryKey() {
        return Keys.SQL160209153452650;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblMiembrosFamiliasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblMiembrosFamiliasRecord>>asList(Keys.SQL160209153452650);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosFamilias as(String alias) {
        return new TblMiembrosFamilias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblMiembrosFamilias rename(String name) {
        return new TblMiembrosFamilias(name, null);
    }
}
