/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblNotasDeCreditoComprasAsientosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNotasDeCreditoComprasAsientos extends TableImpl<TblNotasDeCreditoComprasAsientosRecord> {

    private static final long serialVersionUID = 1403074221;

    /**
     * The reference instance of <code>MG.TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS</code>
     */
    public static final TblNotasDeCreditoComprasAsientos TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS = new TblNotasDeCreditoComprasAsientos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblNotasDeCreditoComprasAsientosRecord> getRecordType() {
        return TblNotasDeCreditoComprasAsientosRecord.class;
    }

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS.ID_NOTA_DE_CREDITO</code>.
     */
    public final TableField<TblNotasDeCreditoComprasAsientosRecord, Integer> ID_NOTA_DE_CREDITO = createField("ID_NOTA_DE_CREDITO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS.ID_ASIENTO</code>.
     */
    public final TableField<TblNotasDeCreditoComprasAsientosRecord, Integer> ID_ASIENTO = createField("ID_ASIENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS</code> table reference
     */
    public TblNotasDeCreditoComprasAsientos() {
        this("TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS</code> table reference
     */
    public TblNotasDeCreditoComprasAsientos(String alias) {
        this(alias, TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS);
    }

    private TblNotasDeCreditoComprasAsientos(String alias, Table<TblNotasDeCreditoComprasAsientosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblNotasDeCreditoComprasAsientos(String alias, Table<TblNotasDeCreditoComprasAsientosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblNotasDeCreditoComprasAsientosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblNotasDeCreditoComprasAsientosRecord, ?>>asList(Keys.SQL160414103609060, Keys.SQL160414103609190);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoComprasAsientos as(String alias) {
        return new TblNotasDeCreditoComprasAsientos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblNotasDeCreditoComprasAsientos rename(String name) {
        return new TblNotasDeCreditoComprasAsientos(name, null);
    }
}
