/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblNotasDeCreditoAsientosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNotasDeCreditoAsientos extends TableImpl<TblNotasDeCreditoAsientosRecord> {

    private static final long serialVersionUID = 1102495574;

    /**
     * The reference instance of <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS</code>
     */
    public static final TblNotasDeCreditoAsientos TBL_NOTAS_DE_CREDITO_ASIENTOS = new TblNotasDeCreditoAsientos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblNotasDeCreditoAsientosRecord> getRecordType() {
        return TblNotasDeCreditoAsientosRecord.class;
    }

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_NOTA_DE_CREDITO</code>.
     */
    public final TableField<TblNotasDeCreditoAsientosRecord, Integer> ID_NOTA_DE_CREDITO = createField("ID_NOTA_DE_CREDITO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_ASIENTO</code>.
     */
    public final TableField<TblNotasDeCreditoAsientosRecord, Integer> ID_ASIENTO = createField("ID_ASIENTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS</code> table reference
     */
    public TblNotasDeCreditoAsientos() {
        this("TBL_NOTAS_DE_CREDITO_ASIENTOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS</code> table reference
     */
    public TblNotasDeCreditoAsientos(String alias) {
        this(alias, TBL_NOTAS_DE_CREDITO_ASIENTOS);
    }

    private TblNotasDeCreditoAsientos(String alias, Table<TblNotasDeCreditoAsientosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblNotasDeCreditoAsientos(String alias, Table<TblNotasDeCreditoAsientosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblNotasDeCreditoAsientosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblNotasDeCreditoAsientosRecord, ?>>asList(Keys.SQL160812163806240, Keys.SQL160812163806400);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoAsientos as(String alias) {
        return new TblNotasDeCreditoAsientos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblNotasDeCreditoAsientos rename(String name) {
        return new TblNotasDeCreditoAsientos(name, null);
    }
}
