/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblNotasDeCreditoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNotasDeCredito extends TableImpl<TblNotasDeCreditoRecord> {

    private static final long serialVersionUID = 1352950240;

    /**
     * The reference instance of <code>MG.TBL_NOTAS_DE_CREDITO</code>
     */
    public static final TblNotasDeCredito TBL_NOTAS_DE_CREDITO = new TblNotasDeCredito();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblNotasDeCreditoRecord> getRecordType() {
        return TblNotasDeCreditoRecord.class;
    }

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.ID</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.NRO</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, String> NRO = createField("NRO", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.ID_TIMBRADO</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Integer> ID_TIMBRADO = createField("ID_TIMBRADO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.FECHAHORA</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.NRO_FACTURA</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Integer> NRO_FACTURA = createField("NRO_FACTURA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.ANULADO</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Boolean> ANULADO = createField("ANULADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("FALSE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MG.TBL_NOTAS_DE_CREDITO.ID_USER</code>.
     */
    public final TableField<TblNotasDeCreditoRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_NOTAS_DE_CREDITO</code> table reference
     */
    public TblNotasDeCredito() {
        this("TBL_NOTAS_DE_CREDITO", null);
    }

    /**
     * Create an aliased <code>MG.TBL_NOTAS_DE_CREDITO</code> table reference
     */
    public TblNotasDeCredito(String alias) {
        this(alias, TBL_NOTAS_DE_CREDITO);
    }

    private TblNotasDeCredito(String alias, Table<TblNotasDeCreditoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblNotasDeCredito(String alias, Table<TblNotasDeCreditoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblNotasDeCreditoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_NOTAS_DE_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblNotasDeCreditoRecord> getPrimaryKey() {
        return Keys.SQL160812163805110;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblNotasDeCreditoRecord>> getKeys() {
        return Arrays.<UniqueKey<TblNotasDeCreditoRecord>>asList(Keys.SQL160812163805110);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblNotasDeCreditoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblNotasDeCreditoRecord, ?>>asList(Keys.SQL160812163805410, Keys.SQL160812163805590, Keys.SQL160812163805890);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCredito as(String alias) {
        return new TblNotasDeCredito(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblNotasDeCredito rename(String name) {
        return new TblNotasDeCredito(name, null);
    }
}
