/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblRecibosCompraFacturasCompraRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosCompraFacturasCompra extends TableImpl<TblRecibosCompraFacturasCompraRecord> {

    private static final long serialVersionUID = 1150309977;

    /**
     * The reference instance of <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA</code>
     */
    public static final TblRecibosCompraFacturasCompra TBL_RECIBOS_COMPRA_FACTURAS_COMPRA = new TblRecibosCompraFacturasCompra();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblRecibosCompraFacturasCompraRecord> getRecordType() {
        return TblRecibosCompraFacturasCompraRecord.class;
    }

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_RECIBO</code>.
     */
    public final TableField<TblRecibosCompraFacturasCompraRecord, Integer> ID_RECIBO = createField("ID_RECIBO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_FACTURA_COMPRA</code>.
     */
    public final TableField<TblRecibosCompraFacturasCompraRecord, Integer> ID_FACTURA_COMPRA = createField("ID_FACTURA_COMPRA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.MONTO</code>.
     */
    public final TableField<TblRecibosCompraFacturasCompraRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA</code> table reference
     */
    public TblRecibosCompraFacturasCompra() {
        this("TBL_RECIBOS_COMPRA_FACTURAS_COMPRA", null);
    }

    /**
     * Create an aliased <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA</code> table reference
     */
    public TblRecibosCompraFacturasCompra(String alias) {
        this(alias, TBL_RECIBOS_COMPRA_FACTURAS_COMPRA);
    }

    private TblRecibosCompraFacturasCompra(String alias, Table<TblRecibosCompraFacturasCompraRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblRecibosCompraFacturasCompra(String alias, Table<TblRecibosCompraFacturasCompraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblRecibosCompraFacturasCompraRecord> getPrimaryKey() {
        return Keys.SQL160818073629000;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblRecibosCompraFacturasCompraRecord>> getKeys() {
        return Arrays.<UniqueKey<TblRecibosCompraFacturasCompraRecord>>asList(Keys.SQL160818073629000);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblRecibosCompraFacturasCompraRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblRecibosCompraFacturasCompraRecord, ?>>asList(Keys.SQL160818073629470, Keys.SQL160818073629640);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraFacturasCompra as(String alias) {
        return new TblRecibosCompraFacturasCompra(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblRecibosCompraFacturasCompra rename(String name) {
        return new TblRecibosCompraFacturasCompra(name, null);
    }
}
