/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblRecibosAsientosTemporalesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosAsientosTemporales extends TableImpl<TblRecibosAsientosTemporalesRecord> {

    private static final long serialVersionUID = 616463853;

    /**
     * The reference instance of <code>MG.TBL_RECIBOS_ASIENTOS_TEMPORALES</code>
     */
    public static final TblRecibosAsientosTemporales TBL_RECIBOS_ASIENTOS_TEMPORALES = new TblRecibosAsientosTemporales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblRecibosAsientosTemporalesRecord> getRecordType() {
        return TblRecibosAsientosTemporalesRecord.class;
    }

    /**
     * The column <code>MG.TBL_RECIBOS_ASIENTOS_TEMPORALES.ID_RECIBO</code>.
     */
    public final TableField<TblRecibosAsientosTemporalesRecord, Integer> ID_RECIBO = createField("ID_RECIBO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_ASIENTOS_TEMPORALES.ID_ASIENTO_TEMPORAL</code>.
     */
    public final TableField<TblRecibosAsientosTemporalesRecord, Integer> ID_ASIENTO_TEMPORAL = createField("ID_ASIENTO_TEMPORAL", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_RECIBOS_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblRecibosAsientosTemporales() {
        this("TBL_RECIBOS_ASIENTOS_TEMPORALES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_RECIBOS_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblRecibosAsientosTemporales(String alias) {
        this(alias, TBL_RECIBOS_ASIENTOS_TEMPORALES);
    }

    private TblRecibosAsientosTemporales(String alias, Table<TblRecibosAsientosTemporalesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblRecibosAsientosTemporales(String alias, Table<TblRecibosAsientosTemporalesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblRecibosAsientosTemporalesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblRecibosAsientosTemporalesRecord, ?>>asList(Keys.SQL160414103610290, Keys.SQL160414103610430);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosAsientosTemporales as(String alias) {
        return new TblRecibosAsientosTemporales(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblRecibosAsientosTemporales rename(String name) {
        return new TblRecibosAsientosTemporales(name, null);
    }
}
