/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblRecibosCompraRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosCompra extends TableImpl<TblRecibosCompraRecord> {

    private static final long serialVersionUID = -976957828;

    /**
     * The reference instance of <code>MG.TBL_RECIBOS_COMPRA</code>
     */
    public static final TblRecibosCompra TBL_RECIBOS_COMPRA = new TblRecibosCompra();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblRecibosCompraRecord> getRecordType() {
        return TblRecibosCompraRecord.class;
    }

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.ID</code>.
     */
    public final TableField<TblRecibosCompraRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.NRO</code>.
     */
    public final TableField<TblRecibosCompraRecord, String> NRO = createField("NRO", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.FECHAHORA</code>.
     */
    public final TableField<TblRecibosCompraRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.RAZON_SOCIAL</code>.
     */
    public final TableField<TblRecibosCompraRecord, String> RAZON_SOCIAL = createField("RAZON_SOCIAL", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.RUC</code>.
     */
    public final TableField<TblRecibosCompraRecord, String> RUC = createField("RUC", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.MONTO</code>.
     */
    public final TableField<TblRecibosCompraRecord, Integer> MONTO = createField("MONTO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.OBSERVACION</code>.
     */
    public final TableField<TblRecibosCompraRecord, String> OBSERVACION = createField("OBSERVACION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>MG.TBL_RECIBOS_COMPRA.ID_USER</code>.
     */
    public final TableField<TblRecibosCompraRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_RECIBOS_COMPRA</code> table reference
     */
    public TblRecibosCompra() {
        this("TBL_RECIBOS_COMPRA", null);
    }

    /**
     * Create an aliased <code>MG.TBL_RECIBOS_COMPRA</code> table reference
     */
    public TblRecibosCompra(String alias) {
        this(alias, TBL_RECIBOS_COMPRA);
    }

    private TblRecibosCompra(String alias, Table<TblRecibosCompraRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblRecibosCompra(String alias, Table<TblRecibosCompraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblRecibosCompraRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_RECIBOS_COMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblRecibosCompraRecord> getPrimaryKey() {
        return Keys.SQL160818073628650;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblRecibosCompraRecord>> getKeys() {
        return Arrays.<UniqueKey<TblRecibosCompraRecord>>asList(Keys.SQL160818073628650);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblRecibosCompraRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblRecibosCompraRecord, ?>>asList(Keys.SQL160818073629290);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompra as(String alias) {
        return new TblRecibosCompra(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblRecibosCompra rename(String name) {
        return new TblRecibosCompra(name, null);
    }
}
