/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblTransferenciasAsientosTemporalesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTransferenciasAsientosTemporales extends TableImpl<TblTransferenciasAsientosTemporalesRecord> {

    private static final long serialVersionUID = 634642815;

    /**
     * The reference instance of <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES</code>
     */
    public static final TblTransferenciasAsientosTemporales TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES = new TblTransferenciasAsientosTemporales();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblTransferenciasAsientosTemporalesRecord> getRecordType() {
        return TblTransferenciasAsientosTemporalesRecord.class;
    }

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_TRANSFERENCIA</code>.
     */
    public final TableField<TblTransferenciasAsientosTemporalesRecord, Integer> ID_TRANSFERENCIA = createField("ID_TRANSFERENCIA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_ASIENTO_TEMPORAL</code>.
     */
    public final TableField<TblTransferenciasAsientosTemporalesRecord, Integer> ID_ASIENTO_TEMPORAL = createField("ID_ASIENTO_TEMPORAL", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblTransferenciasAsientosTemporales() {
        this("TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES", null);
    }

    /**
     * Create an aliased <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES</code> table reference
     */
    public TblTransferenciasAsientosTemporales(String alias) {
        this(alias, TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES);
    }

    private TblTransferenciasAsientosTemporales(String alias, Table<TblTransferenciasAsientosTemporalesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblTransferenciasAsientosTemporales(String alias, Table<TblTransferenciasAsientosTemporalesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblTransferenciasAsientosTemporalesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblTransferenciasAsientosTemporalesRecord, ?>>asList(Keys.SQL160414103609910, Keys.SQL160414103610080);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTransferenciasAsientosTemporales as(String alias) {
        return new TblTransferenciasAsientosTemporales(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblTransferenciasAsientosTemporales rename(String name) {
        return new TblTransferenciasAsientosTemporales(name, null);
    }
}
