/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblTimbradosRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTimbrados extends TableImpl<TblTimbradosRecord> {

    private static final long serialVersionUID = 575843580;

    /**
     * The reference instance of <code>MG.TBL_TIMBRADOS</code>
     */
    public static final TblTimbrados TBL_TIMBRADOS = new TblTimbrados();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblTimbradosRecord> getRecordType() {
        return TblTimbradosRecord.class;
    }

    /**
     * The column <code>MG.TBL_TIMBRADOS.NRO</code>.
     */
    public final TableField<TblTimbradosRecord, Integer> NRO = createField("NRO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.FECHA_INICIO</code>.
     */
    public final TableField<TblTimbradosRecord, Timestamp> FECHA_INICIO = createField("FECHA_INICIO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.FECHA_VENCIMIENTO</code>.
     */
    public final TableField<TblTimbradosRecord, Timestamp> FECHA_VENCIMIENTO = createField("FECHA_VENCIMIENTO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.NRO_FACTURA_INCIO</code>.
     */
    public final TableField<TblTimbradosRecord, Integer> NRO_FACTURA_INCIO = createField("NRO_FACTURA_INCIO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.NRO_FACTURA_FIN</code>.
     */
    public final TableField<TblTimbradosRecord, Integer> NRO_FACTURA_FIN = createField("NRO_FACTURA_FIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.ACTIVO</code>.
     */
    public final TableField<TblTimbradosRecord, Boolean> ACTIVO = createField("ACTIVO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS.ID_USER</code>.
     */
    public final TableField<TblTimbradosRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_TIMBRADOS</code> table reference
     */
    public TblTimbrados() {
        this("TBL_TIMBRADOS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_TIMBRADOS</code> table reference
     */
    public TblTimbrados(String alias) {
        this(alias, TBL_TIMBRADOS);
    }

    private TblTimbrados(String alias, Table<TblTimbradosRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblTimbrados(String alias, Table<TblTimbradosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblTimbradosRecord> getPrimaryKey() {
        return Keys.SQL160209153456210;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblTimbradosRecord>> getKeys() {
        return Arrays.<UniqueKey<TblTimbradosRecord>>asList(Keys.SQL160209153456210);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblTimbradosRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblTimbradosRecord, ?>>asList(Keys.SQL160209153501880);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbrados as(String alias) {
        return new TblTimbrados(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblTimbrados rename(String name) {
        return new TblTimbrados(name, null);
    }
}
