/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblTransferenciasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTransferencias extends TableImpl<TblTransferenciasRecord> {

    private static final long serialVersionUID = 1635374266;

    /**
     * The reference instance of <code>MG.TBL_TRANSFERENCIAS</code>
     */
    public static final TblTransferencias TBL_TRANSFERENCIAS = new TblTransferencias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblTransferenciasRecord> getRecordType() {
        return TblTransferenciasRecord.class;
    }

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.FECHAHORA</code>.
     */
    public final TableField<TblTransferenciasRecord, Timestamp> FECHAHORA = createField("FECHAHORA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.CONCEPTO</code>.
     */
    public final TableField<TblTransferenciasRecord, String> CONCEPTO = createField("CONCEPTO", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.MONTO_APORTE</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> MONTO_APORTE = createField("MONTO_APORTE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.MONTO_DONACION</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> MONTO_DONACION = createField("MONTO_DONACION", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID_ENTIDAD</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID_ENTIDAD = createField("ID_ENTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID_EVENTO_TIPO</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID_EVENTO_TIPO = createField("ID_EVENTO_TIPO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.COBRADO</code>.
     */
    public final TableField<TblTransferenciasRecord, Boolean> COBRADO = createField("COBRADO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("FALSE", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID_USER</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID_EVENTO</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID_EVENTO = createField("ID_EVENTO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.FECHAHORA_COMPROMISO</code>.
     */
    public final TableField<TblTransferenciasRecord, Timestamp> FECHAHORA_COMPROMISO = createField("FECHAHORA_COMPROMISO", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.ID_EVENTO_DETALLE</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> ID_EVENTO_DETALLE = createField("ID_EVENTO_DETALLE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MG.TBL_TRANSFERENCIAS.SEQ_PAGO</code>.
     */
    public final TableField<TblTransferenciasRecord, Integer> SEQ_PAGO = createField("SEQ_PAGO", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>MG.TBL_TRANSFERENCIAS</code> table reference
     */
    public TblTransferencias() {
        this("TBL_TRANSFERENCIAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_TRANSFERENCIAS</code> table reference
     */
    public TblTransferencias(String alias) {
        this(alias, TBL_TRANSFERENCIAS);
    }

    private TblTransferencias(String alias, Table<TblTransferenciasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblTransferencias(String alias, Table<TblTransferenciasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblTransferenciasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_TRANSFERENCIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblTransferenciasRecord> getPrimaryKey() {
        return Keys.SQL160224153129850;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblTransferenciasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblTransferenciasRecord>>asList(Keys.SQL160224153129850);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblTransferenciasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblTransferenciasRecord, ?>>asList(Keys.SQL160224153130590, Keys.SQL160224153130750, Keys.SQL160224153130900, Keys.SQL160414103545940, Keys.SQL160922065248510);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTransferencias as(String alias) {
        return new TblTransferencias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblTransferencias rename(String name) {
        return new TblTransferencias(name, null);
    }
}
