/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblTimbradosNotasDeCreditoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTimbradosNotasDeCredito extends TableImpl<TblTimbradosNotasDeCreditoRecord> {

    private static final long serialVersionUID = -1514248212;

    /**
     * The reference instance of <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO</code>
     */
    public static final TblTimbradosNotasDeCredito TBL_TIMBRADOS_NOTAS_DE_CREDITO = new TblTimbradosNotasDeCredito();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblTimbradosNotasDeCreditoRecord> getRecordType() {
        return TblTimbradosNotasDeCreditoRecord.class;
    }

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.ID</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.NRO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, String> NRO = createField("NRO", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.ESTABLECIMIENTO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, String> ESTABLECIMIENTO = createField("ESTABLECIMIENTO", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.PUNTO_DE_EXPEDICION</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, String> PUNTO_DE_EXPEDICION = createField("PUNTO_DE_EXPEDICION", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.FECHA_INICIO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Timestamp> FECHA_INICIO = createField("FECHA_INICIO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.FECHA_VENCIMIENTO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Timestamp> FECHA_VENCIMIENTO = createField("FECHA_VENCIMIENTO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.NRO_NOTA_DE_CREDITO_INCIO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Integer> NRO_NOTA_DE_CREDITO_INCIO = createField("NRO_NOTA_DE_CREDITO_INCIO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.NRO_NOTA_DE_CREDITO_FIN</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Integer> NRO_NOTA_DE_CREDITO_FIN = createField("NRO_NOTA_DE_CREDITO_FIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.ACTIVO</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Boolean> ACTIVO = createField("ACTIVO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO.ID_USER</code>.
     */
    public final TableField<TblTimbradosNotasDeCreditoRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO</code> table reference
     */
    public TblTimbradosNotasDeCredito() {
        this("TBL_TIMBRADOS_NOTAS_DE_CREDITO", null);
    }

    /**
     * Create an aliased <code>MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO</code> table reference
     */
    public TblTimbradosNotasDeCredito(String alias) {
        this(alias, TBL_TIMBRADOS_NOTAS_DE_CREDITO);
    }

    private TblTimbradosNotasDeCredito(String alias, Table<TblTimbradosNotasDeCreditoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblTimbradosNotasDeCredito(String alias, Table<TblTimbradosNotasDeCreditoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblTimbradosNotasDeCreditoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_TIMBRADOS_NOTAS_DE_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblTimbradosNotasDeCreditoRecord> getPrimaryKey() {
        return Keys.SQL160812163804520;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblTimbradosNotasDeCreditoRecord>> getKeys() {
        return Arrays.<UniqueKey<TblTimbradosNotasDeCreditoRecord>>asList(Keys.SQL160812163804520);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblTimbradosNotasDeCreditoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblTimbradosNotasDeCreditoRecord, ?>>asList(Keys.SQL160812163804890);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosNotasDeCredito as(String alias) {
        return new TblTimbradosNotasDeCredito(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblTimbradosNotasDeCredito rename(String name) {
        return new TblTimbradosNotasDeCredito(name, null);
    }
}
