/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables;


import com.gnadenheimer.mg3.domain.jooq.Keys;
import com.gnadenheimer.mg3.domain.jooq.Mg;
import com.gnadenheimer.mg3.domain.jooq.tables.records.TblTimbradosAutofacturasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTimbradosAutofacturas extends TableImpl<TblTimbradosAutofacturasRecord> {

    private static final long serialVersionUID = -983241268;

    /**
     * The reference instance of <code>MG.TBL_TIMBRADOS_AUTOFACTURAS</code>
     */
    public static final TblTimbradosAutofacturas TBL_TIMBRADOS_AUTOFACTURAS = new TblTimbradosAutofacturas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblTimbradosAutofacturasRecord> getRecordType() {
        return TblTimbradosAutofacturasRecord.class;
    }

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.ID</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.NRO</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, String> NRO = createField("NRO", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.FECHA_INICIO</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Timestamp> FECHA_INICIO = createField("FECHA_INICIO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.FECHA_VENCIMIENTO</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Timestamp> FECHA_VENCIMIENTO = createField("FECHA_VENCIMIENTO", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.NRO_FACTURA_INCIO</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Integer> NRO_FACTURA_INCIO = createField("NRO_FACTURA_INCIO", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.NRO_FACTURA_FIN</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Integer> NRO_FACTURA_FIN = createField("NRO_FACTURA_FIN", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.ACTIVO</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Boolean> ACTIVO = createField("ACTIVO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>MG.TBL_TIMBRADOS_AUTOFACTURAS.ID_USER</code>.
     */
    public final TableField<TblTimbradosAutofacturasRecord, Integer> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>MG.TBL_TIMBRADOS_AUTOFACTURAS</code> table reference
     */
    public TblTimbradosAutofacturas() {
        this("TBL_TIMBRADOS_AUTOFACTURAS", null);
    }

    /**
     * Create an aliased <code>MG.TBL_TIMBRADOS_AUTOFACTURAS</code> table reference
     */
    public TblTimbradosAutofacturas(String alias) {
        this(alias, TBL_TIMBRADOS_AUTOFACTURAS);
    }

    private TblTimbradosAutofacturas(String alias, Table<TblTimbradosAutofacturasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblTimbradosAutofacturas(String alias, Table<TblTimbradosAutofacturasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mg.MG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblTimbradosAutofacturasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_TIMBRADOS_AUTOFACTURAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblTimbradosAutofacturasRecord> getPrimaryKey() {
        return Keys.SQL160414103607640;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblTimbradosAutofacturasRecord>> getKeys() {
        return Arrays.<UniqueKey<TblTimbradosAutofacturasRecord>>asList(Keys.SQL160414103607640);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblTimbradosAutofacturasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblTimbradosAutofacturasRecord, ?>>asList(Keys.SQL160414103614300);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosAutofacturas as(String alias) {
        return new TblTimbradosAutofacturas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblTimbradosAutofacturas rename(String name) {
        return new TblTimbradosAutofacturas(name, null);
    }
}
