ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD COLUMN FECHAHORA_COMPROMISO TIMESTAMP;

UPDATE MG.TBL_TRANSFERENCIAS SET FECHAHORA_COMPROMISO = FECHAHORA;

ALTER TABLE MG.TBL_RECIBOS
	ADD COLUMN FECHAHORA_COMPROMISO TIMESTAMP;

UPDATE MG.TBL_RECIBOS SET FECHAHORA_COMPROMISO = FECHAHORA;