/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.Recibo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReciboRecord extends TableRecordImpl<ReciboRecord> implements Record5<Integer, Timestamp, String, String, Integer> {

    private static final long serialVersionUID = -440971197;

    /**
     * Setter for <code>MG.RECIBO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.RECIBO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.RECIBO.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.RECIBO.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.RECIBO.NOMBRE</code>.
     */
    public void setNombre(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.RECIBO.NOMBRE</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.RECIBO.CONCEPTO</code>.
     */
    public void setConcepto(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.RECIBO.CONCEPTO</code>.
     */
    public String getConcepto() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MG.RECIBO.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.RECIBO.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Recibo.RECIBO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Recibo.RECIBO.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Recibo.RECIBO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Recibo.RECIBO.CONCEPTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Recibo.RECIBO.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord value3(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord value4(String value) {
        setConcepto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord value5(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReciboRecord values(Integer value1, Timestamp value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReciboRecord
     */
    public ReciboRecord() {
        super(Recibo.RECIBO);
    }

    /**
     * Create a detached, initialised ReciboRecord
     */
    public ReciboRecord(Integer id, Timestamp fechahora, String nombre, String concepto, Integer monto) {
        super(Recibo.RECIBO);

        set(0, id);
        set(1, fechahora);
        set(2, nombre);
        set(3, concepto);
        set(4, monto);
    }
}
