/*
 * This file is generated by jOOQ.
 */
package com.gnadenheimer.mg3.domain.jooq.tables.records;

import com.gnadenheimer.mg3.domain.jooq.tables.TblAsientos;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
            "http://www.jooq.org",
            "jOOQ version:3.9.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TblAsientosRecord extends UpdatableRecordImpl<TblAsientosRecord> implements Record10<Integer, Timestamp, Integer, Integer, String, Integer, Integer, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 123693378;

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID_CUENTA_CONTABLE_DEBE</code>.
     */
    public void setIdCuentaContableDebe(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID_CUENTA_CONTABLE_DEBE</code>.
     */
    public Integer getIdCuentaContableDebe() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID_CUENTA_CONTABLE_HABER</code>.
     */
    public void setIdCuentaContableHaber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID_CUENTA_CONTABLE_HABER</code>.
     */
    public Integer getIdCuentaContableHaber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.OBSERVACION</code>.
     */
    public void setObservacion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.OBSERVACION</code>.
     */
    public String getObservacion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ASIENTO_MANUAL</code>.
     */
    public void setAsientoManual(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ASIENTO_MANUAL</code>.
     */
    public Boolean getAsientoManual() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_DEBE</code>.
     */
    public void setIdCentroDeCostoDebe(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_DEBE</code>.
     */
    public Integer getIdCentroDeCostoDebe() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_HABER</code>.
     */
    public void setIdCentroDeCostoHaber(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_HABER</code>.
     */
    public Integer getIdCentroDeCostoHaber() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------
    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------
    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Timestamp, Integer, Integer, String, Integer, Integer, Boolean, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Timestamp, Integer, Integer, String, Integer, Integer, Boolean, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAsientos.TBL_ASIENTOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblAsientos.TBL_ASIENTOS.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblAsientos.TBL_ASIENTOS.ID_CUENTA_CONTABLE_DEBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblAsientos.TBL_ASIENTOS.ID_CUENTA_CONTABLE_HABER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblAsientos.TBL_ASIENTOS.OBSERVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblAsientos.TBL_ASIENTOS.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblAsientos.TBL_ASIENTOS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return TblAsientos.TBL_ASIENTOS.ASIENTO_MANUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblAsientos.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_DEBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TblAsientos.TBL_ASIENTOS.ID_CENTRO_DE_COSTO_HABER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCuentaContableDebe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdCuentaContableHaber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getAsientoManual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdCentroDeCostoDebe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIdCentroDeCostoHaber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value3(Integer value) {
        setIdCuentaContableDebe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value4(Integer value) {
        setIdCuentaContableHaber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value5(String value) {
        setObservacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value6(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value7(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value8(Boolean value) {
        setAsientoManual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value9(Integer value) {
        setIdCentroDeCostoDebe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord value10(Integer value) {
        setIdCentroDeCostoHaber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, String value5, Integer value6, Integer value7, Boolean value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------
    /**
     * Create a detached TblAsientosRecord
     */
    public TblAsientosRecord() {
        super(TblAsientos.TBL_ASIENTOS);
    }

    /**
     * Create a detached, initialised TblAsientosRecord
     */
    public TblAsientosRecord(Integer id, Timestamp fechahora, Integer idCuentaContableDebe, Integer idCuentaContableHaber, String observacion, Integer monto, Integer idUser, Boolean asientoManual, Integer idCentroDeCostoDebe, Integer idCentroDeCostoHaber) {
        super(TblAsientos.TBL_ASIENTOS);

        set(0, id);
        set(1, fechahora);
        set(2, idCuentaContableDebe);
        set(3, idCuentaContableHaber);
        set(4, observacion);
        set(5, monto);
        set(6, idUser);
        set(7, asientoManual);
        set(8, idCentroDeCostoDebe);
        set(9, idCentroDeCostoHaber);
    }
}
