/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblAutofacturasAsientos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAutofacturasAsientosRecord extends TableRecordImpl<TblAutofacturasAsientosRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 503095757;

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_AUTOFACTURA</code>.
     */
    public void setIdAutofactura(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_AUTOFACTURA</code>.
     */
    public Integer getIdAutofactura() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_ASIENTO</code>.
     */
    public void setIdAsiento(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS_ASIENTOS.ID_ASIENTO</code>.
     */
    public Integer getIdAsiento() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAutofacturasAsientos.TBL_AUTOFACTURAS_ASIENTOS.ID_AUTOFACTURA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblAutofacturasAsientos.TBL_AUTOFACTURAS_ASIENTOS.ID_ASIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdAutofactura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdAsiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasAsientosRecord value1(Integer value) {
        setIdAutofactura(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasAsientosRecord value2(Integer value) {
        setIdAsiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasAsientosRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblAutofacturasAsientosRecord
     */
    public TblAutofacturasAsientosRecord() {
        super(TblAutofacturasAsientos.TBL_AUTOFACTURAS_ASIENTOS);
    }

    /**
     * Create a detached, initialised TblAutofacturasAsientosRecord
     */
    public TblAutofacturasAsientosRecord(Integer idAutofactura, Integer idAsiento) {
        super(TblAutofacturasAsientos.TBL_AUTOFACTURAS_ASIENTOS);

        set(0, idAutofactura);
        set(1, idAsiento);
    }
}
