/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblAsientosTemporales;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAsientosTemporalesRecord extends UpdatableRecordImpl<TblAsientosTemporalesRecord> implements Record9<Integer, Timestamp, Integer, Integer, Integer, Boolean, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 300788341;

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_DEBE</code>.
     */
    public void setIdCuentaContableDebe(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_DEBE</code>.
     */
    public Integer getIdCuentaContableDebe() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_HABER</code>.
     */
    public void setIdCuentaContableHaber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_HABER</code>.
     */
    public Integer getIdCuentaContableHaber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ES_APORTE</code>.
     */
    public void setEsAporte(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ES_APORTE</code>.
     */
    public Boolean getEsAporte() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.FACTURADO</code>.
     */
    public void setFacturado(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.FACTURADO</code>.
     */
    public Boolean getFacturado() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_DEBE</code>.
     */
    public void setIdCentroDeCostoDebe(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_DEBE</code>.
     */
    public Integer getIdCentroDeCostoDebe() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_HABER</code>.
     */
    public void setIdCentroDeCostoHaber(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_HABER</code>.
     */
    public Integer getIdCentroDeCostoHaber() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, Integer, Integer, Integer, Boolean, Boolean, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, Integer, Integer, Integer, Boolean, Boolean, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_DEBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ID_CUENTA_CONTABLE_HABER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ES_APORTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.FACTURADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_DEBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES.ID_CENTRO_DE_COSTO_HABER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCuentaContableDebe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdCuentaContableHaber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getEsAporte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getFacturado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdCentroDeCostoDebe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdCentroDeCostoHaber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value3(Integer value) {
        setIdCuentaContableDebe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value4(Integer value) {
        setIdCuentaContableHaber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value5(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value6(Boolean value) {
        setEsAporte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value7(Boolean value) {
        setFacturado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value8(Integer value) {
        setIdCentroDeCostoDebe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord value9(Integer value) {
        setIdCentroDeCostoHaber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAsientosTemporalesRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, Integer value5, Boolean value6, Boolean value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblAsientosTemporalesRecord
     */
    public TblAsientosTemporalesRecord() {
        super(TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES);
    }

    /**
     * Create a detached, initialised TblAsientosTemporalesRecord
     */
    public TblAsientosTemporalesRecord(Integer id, Timestamp fechahora, Integer idCuentaContableDebe, Integer idCuentaContableHaber, Integer monto, Boolean esAporte, Boolean facturado, Integer idCentroDeCostoDebe, Integer idCentroDeCostoHaber) {
        super(TblAsientosTemporales.TBL_ASIENTOS_TEMPORALES);

        set(0, id);
        set(1, fechahora);
        set(2, idCuentaContableDebe);
        set(3, idCuentaContableHaber);
        set(4, monto);
        set(5, esAporte);
        set(6, facturado);
        set(7, idCentroDeCostoDebe);
        set(8, idCentroDeCostoHaber);
    }
}
