/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblAreasServicioEnIglesia;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAreasServicioEnIglesiaRecord extends UpdatableRecordImpl<TblAreasServicioEnIglesiaRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 2000155503;

    /**
     * Setter for <code>MG.TBL_AREAS_SERVICIO_EN_IGLESIA.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_AREAS_SERVICIO_EN_IGLESIA.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_AREAS_SERVICIO_EN_IGLESIA.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_AREAS_SERVICIO_EN_IGLESIA.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAreasServicioEnIglesia.TBL_AREAS_SERVICIO_EN_IGLESIA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblAreasServicioEnIglesia.TBL_AREAS_SERVICIO_EN_IGLESIA.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAreasServicioEnIglesiaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAreasServicioEnIglesiaRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAreasServicioEnIglesiaRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblAreasServicioEnIglesiaRecord
     */
    public TblAreasServicioEnIglesiaRecord() {
        super(TblAreasServicioEnIglesia.TBL_AREAS_SERVICIO_EN_IGLESIA);
    }

    /**
     * Create a detached, initialised TblAreasServicioEnIglesiaRecord
     */
    public TblAreasServicioEnIglesiaRecord(Integer id, String descripcion) {
        super(TblAreasServicioEnIglesia.TBL_AREAS_SERVICIO_EN_IGLESIA);

        set(0, id);
        set(1, descripcion);
    }
}
