/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblAutofacturas;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAutofacturasRecord extends UpdatableRecordImpl<TblAutofacturasRecord> implements Record16<Integer, String, Integer, Timestamp, String, String, String, String, Integer, String, Integer, Integer, String, Boolean, Integer, Boolean> {

    private static final long serialVersionUID = 340809244;

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.NRO</code>.
     */
    public void setNro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.NRO</code>.
     */
    public String getNro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.ID_TIMBRADO</code>.
     */
    public void setIdTimbrado(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.ID_TIMBRADO</code>.
     */
    public Integer getIdTimbrado() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.NOMBRE</code>.
     */
    public void setNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.NOMBRE</code>.
     */
    public String getNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.DOMICILIO</code>.
     */
    public void setDomicilio(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.DOMICILIO</code>.
     */
    public String getDomicilio() {
        return (String) get(5);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.DIRECCION_DE_TRANSACCION</code>.
     */
    public void setDireccionDeTransaccion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.DIRECCION_DE_TRANSACCION</code>.
     */
    public String getDireccionDeTransaccion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.CI</code>.
     */
    public void setCi(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.CI</code>.
     */
    public String getCi() {
        return (String) get(7);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.CANTIDAD</code>.
     */
    public void setCantidad(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.CANTIDAD</code>.
     */
    public Integer getCantidad() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.CONCEPTO</code>.
     */
    public void setConcepto(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.CONCEPTO</code>.
     */
    public String getConcepto() {
        return (String) get(9);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.PRECIO_UNITARIO</code>.
     */
    public void setPrecioUnitario(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.PRECIO_UNITARIO</code>.
     */
    public Integer getPrecioUnitario() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.OBSERVACION</code>.
     */
    public void setObservacion(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.OBSERVACION</code>.
     */
    public String getObservacion() {
        return (String) get(12);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.ANULADO</code>.
     */
    public void setAnulado(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.ANULADO</code>.
     */
    public Boolean getAnulado() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>MG.TBL_AUTOFACTURAS.CONDICION_CONTADO</code>.
     */
    public void setCondicionContado(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>MG.TBL_AUTOFACTURAS.CONDICION_CONTADO</code>.
     */
    public Boolean getCondicionContado() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, Timestamp, String, String, String, String, Integer, String, Integer, Integer, String, Boolean, Integer, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, Integer, Timestamp, String, String, String, String, Integer, String, Integer, Integer, String, Boolean, Integer, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAutofacturas.TBL_AUTOFACTURAS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblAutofacturas.TBL_AUTOFACTURAS.NRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblAutofacturas.TBL_AUTOFACTURAS.ID_TIMBRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TblAutofacturas.TBL_AUTOFACTURAS.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblAutofacturas.TBL_AUTOFACTURAS.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TblAutofacturas.TBL_AUTOFACTURAS.DOMICILIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TblAutofacturas.TBL_AUTOFACTURAS.DIRECCION_DE_TRANSACCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TblAutofacturas.TBL_AUTOFACTURAS.CI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblAutofacturas.TBL_AUTOFACTURAS.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TblAutofacturas.TBL_AUTOFACTURAS.CONCEPTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TblAutofacturas.TBL_AUTOFACTURAS.PRECIO_UNITARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return TblAutofacturas.TBL_AUTOFACTURAS.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TblAutofacturas.TBL_AUTOFACTURAS.OBSERVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return TblAutofacturas.TBL_AUTOFACTURAS.ANULADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TblAutofacturas.TBL_AUTOFACTURAS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return TblAutofacturas.TBL_AUTOFACTURAS.CONDICION_CONTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdTimbrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDireccionDeTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPrecioUnitario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getAnulado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getCondicionContado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value2(String value) {
        setNro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value3(Integer value) {
        setIdTimbrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value4(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value5(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value6(String value) {
        setDomicilio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value7(String value) {
        setDireccionDeTransaccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value8(String value) {
        setCi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value9(Integer value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value10(String value) {
        setConcepto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value11(Integer value) {
        setPrecioUnitario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value12(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value13(String value) {
        setObservacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value14(Boolean value) {
        setAnulado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value15(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord value16(Boolean value) {
        setCondicionContado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAutofacturasRecord values(Integer value1, String value2, Integer value3, Timestamp value4, String value5, String value6, String value7, String value8, Integer value9, String value10, Integer value11, Integer value12, String value13, Boolean value14, Integer value15, Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblAutofacturasRecord
     */
    public TblAutofacturasRecord() {
        super(TblAutofacturas.TBL_AUTOFACTURAS);
    }

    /**
     * Create a detached, initialised TblAutofacturasRecord
     */
    public TblAutofacturasRecord(Integer id, String nro, Integer idTimbrado, Timestamp fechahora, String nombre, String domicilio, String direccionDeTransaccion, String ci, Integer cantidad, String concepto, Integer precioUnitario, Integer monto, String observacion, Boolean anulado, Integer idUser, Boolean condicionContado) {
        super(TblAutofacturas.TBL_AUTOFACTURAS);

        set(0, id);
        set(1, nro);
        set(2, idTimbrado);
        set(3, fechahora);
        set(4, nombre);
        set(5, domicilio);
        set(6, direccionDeTransaccion);
        set(7, ci);
        set(8, cantidad);
        set(9, concepto);
        set(10, precioUnitario);
        set(11, monto);
        set(12, observacion);
        set(13, anulado);
        set(14, idUser);
        set(15, condicionContado);
    }
}
