/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblAportesImporteMensualSaldoAnterior;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblAportesImporteMensualSaldoAnteriorRecord extends UpdatableRecordImpl<TblAportesImporteMensualSaldoAnteriorRecord> implements Record5<Integer, Integer, Integer, Long, Long> {

    private static final long serialVersionUID = -1134702250;

    /**
     * Setter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID_ENTIDAD</code>.
     */
    public void setIdEntidad(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID_ENTIDAD</code>.
     */
    public Integer getIdEntidad() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ANO</code>.
     */
    public void setAno(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ANO</code>.
     */
    public Integer getAno() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.IMPORTE_MESNUAL</code>.
     */
    public void setImporteMesnual(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.IMPORTE_MESNUAL</code>.
     */
    public Long getImporteMesnual() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.SALDO_ANTERIOR</code>.
     */
    public void setSaldoAnterior(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.SALDO_ANTERIOR</code>.
     */
    public Long getSaldoAnterior() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ID_ENTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.ANO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.IMPORTE_MESNUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR.SALDO_ANTERIOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdEntidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getImporteMesnual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSaldoAnterior();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord value2(Integer value) {
        setIdEntidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord value3(Integer value) {
        setAno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord value4(Long value) {
        setImporteMesnual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord value5(Long value) {
        setSaldoAnterior(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblAportesImporteMensualSaldoAnteriorRecord values(Integer value1, Integer value2, Integer value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblAportesImporteMensualSaldoAnteriorRecord
     */
    public TblAportesImporteMensualSaldoAnteriorRecord() {
        super(TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR);
    }

    /**
     * Create a detached, initialised TblAportesImporteMensualSaldoAnteriorRecord
     */
    public TblAportesImporteMensualSaldoAnteriorRecord(Integer id, Integer idEntidad, Integer ano, Long importeMesnual, Long saldoAnterior) {
        super(TblAportesImporteMensualSaldoAnterior.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR);

        set(0, id);
        set(1, idEntidad);
        set(2, ano);
        set(3, importeMesnual);
        set(4, saldoAnterior);
    }
}
