/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblCentrosDeCosto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCentrosDeCostoRecord extends UpdatableRecordImpl<TblCentrosDeCostoRecord> implements Record7<Integer, String, Integer, Integer, Integer, Boolean, Boolean> {

    private static final long serialVersionUID = -625439224;

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_EFECTIVO_POR_DEFECTO</code>.
     */
    public void setIdCuentaContableEfectivoPorDefecto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_EFECTIVO_POR_DEFECTO</code>.
     */
    public Integer getIdCuentaContableEfectivoPorDefecto() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_CTA_CTE_POR_DEFECTO</code>.
     */
    public void setIdCuentaContableCtaCtePorDefecto(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_CTA_CTE_POR_DEFECTO</code>.
     */
    public Integer getIdCuentaContableCtaCtePorDefecto() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.CTA_CTE</code>.
     */
    public void setCtaCte(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.CTA_CTE</code>.
     */
    public Integer getCtaCte() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.PREFERIDO</code>.
     */
    public void setPreferido(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.PREFERIDO</code>.
     */
    public Boolean getPreferido() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>MG.TBL_CENTROS_DE_COSTO.ES_DONACION_EXTERNA</code>.
     */
    public void setEsDonacionExterna(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_CENTROS_DE_COSTO.ES_DONACION_EXTERNA</code>.
     */
    public Boolean getEsDonacionExterna() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, Boolean, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, Boolean, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_EFECTIVO_POR_DEFECTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.ID_CUENTA_CONTABLE_CTA_CTE_POR_DEFECTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.CTA_CTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.PREFERIDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return TblCentrosDeCosto.TBL_CENTROS_DE_COSTO.ES_DONACION_EXTERNA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCuentaContableEfectivoPorDefecto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdCuentaContableCtaCtePorDefecto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCtaCte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getPreferido();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getEsDonacionExterna();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value3(Integer value) {
        setIdCuentaContableEfectivoPorDefecto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value4(Integer value) {
        setIdCuentaContableCtaCtePorDefecto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value5(Integer value) {
        setCtaCte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value6(Boolean value) {
        setPreferido(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord value7(Boolean value) {
        setEsDonacionExterna(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCentrosDeCostoRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Boolean value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblCentrosDeCostoRecord
     */
    public TblCentrosDeCostoRecord() {
        super(TblCentrosDeCosto.TBL_CENTROS_DE_COSTO);
    }

    /**
     * Create a detached, initialised TblCentrosDeCostoRecord
     */
    public TblCentrosDeCostoRecord(Integer id, String descripcion, Integer idCuentaContableEfectivoPorDefecto, Integer idCuentaContableCtaCtePorDefecto, Integer ctaCte, Boolean preferido, Boolean esDonacionExterna) {
        super(TblCentrosDeCosto.TBL_CENTROS_DE_COSTO);

        set(0, id);
        set(1, descripcion);
        set(2, idCuentaContableEfectivoPorDefecto);
        set(3, idCuentaContableCtaCtePorDefecto);
        set(4, ctaCte);
        set(5, preferido);
        set(6, esDonacionExterna);
    }
}
