/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblCuentasContablesPorDefecto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCuentasContablesPorDefectoRecord extends UpdatableRecordImpl<TblCuentasContablesPorDefectoRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1801820501;

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO</code>.
     */
    public void setIdCuentaHaberComprasFacturaContado(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO</code>.
     */
    public Integer getIdCuentaHaberComprasFacturaContado() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO</code>.
     */
    public void setIdCuentaHaberComprasFacturaCredito(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO</code>.
     */
    public Integer getIdCuentaHaberComprasFacturaCredito() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DEBE_COMPRAS</code>.
     */
    public void setIdCuentaDebeCompras(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DEBE_COMPRAS</code>.
     */
    public Integer getIdCuentaDebeCompras() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_A_COBRAR</code>.
     */
    public void setIdCuentaACobrar(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_A_COBRAR</code>.
     */
    public Integer getIdCuentaACobrar() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_APORTES</code>.
     */
    public void setIdCuentaAportes(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_APORTES</code>.
     */
    public Integer getIdCuentaAportes() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DONACIONES</code>.
     */
    public void setIdCuentaDonaciones(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DONACIONES</code>.
     */
    public Integer getIdCuentaDonaciones() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CAJA</code>.
     */
    public void setIdCuentaCaja(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CAJA</code>.
     */
    public Integer getIdCuentaCaja() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CTA_CTE</code>.
     */
    public void setIdCuentaCtaCte(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CTA_CTE</code>.
     */
    public Integer getIdCuentaCtaCte() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CONTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_HABER_COMPRAS_FACTURA_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DEBE_COMPRAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_A_COBRAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_APORTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_DONACIONES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CAJA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO.ID_CUENTA_CTA_CTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdCuentaHaberComprasFacturaContado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCuentaHaberComprasFacturaCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdCuentaDebeCompras();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdCuentaACobrar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdCuentaAportes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdCuentaDonaciones();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdCuentaCaja();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdCuentaCtaCte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value2(Integer value) {
        setIdCuentaHaberComprasFacturaContado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value3(Integer value) {
        setIdCuentaHaberComprasFacturaCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value4(Integer value) {
        setIdCuentaDebeCompras(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value5(Integer value) {
        setIdCuentaACobrar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value6(Integer value) {
        setIdCuentaAportes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value7(Integer value) {
        setIdCuentaDonaciones(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value8(Integer value) {
        setIdCuentaCaja(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord value9(Integer value) {
        setIdCuentaCtaCte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesPorDefectoRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblCuentasContablesPorDefectoRecord
     */
    public TblCuentasContablesPorDefectoRecord() {
        super(TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO);
    }

    /**
     * Create a detached, initialised TblCuentasContablesPorDefectoRecord
     */
    public TblCuentasContablesPorDefectoRecord(Integer id, Integer idCuentaHaberComprasFacturaContado, Integer idCuentaHaberComprasFacturaCredito, Integer idCuentaDebeCompras, Integer idCuentaACobrar, Integer idCuentaAportes, Integer idCuentaDonaciones, Integer idCuentaCaja, Integer idCuentaCtaCte) {
        super(TblCuentasContablesPorDefecto.TBL_CUENTAS_CONTABLES_POR_DEFECTO);

        set(0, id);
        set(1, idCuentaHaberComprasFacturaContado);
        set(2, idCuentaHaberComprasFacturaCredito);
        set(3, idCuentaDebeCompras);
        set(4, idCuentaACobrar);
        set(5, idCuentaAportes);
        set(6, idCuentaDonaciones);
        set(7, idCuentaCaja);
        set(8, idCuentaCtaCte);
    }
}
