/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblCuentasContables;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblCuentasContablesRecord extends UpdatableRecordImpl<TblCuentasContablesRecord> implements Record4<Integer, String, Integer, Boolean> {

    private static final long serialVersionUID = -1683660571;

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES.ID_CUENTA_MADRE</code>.
     */
    public void setIdCuentaMadre(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES.ID_CUENTA_MADRE</code>.
     */
    public Integer getIdCuentaMadre() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_CUENTAS_CONTABLES.IMPUTABLE</code>.
     */
    public void setImputable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_CUENTAS_CONTABLES.IMPUTABLE</code>.
     */
    public Boolean getImputable() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblCuentasContables.TBL_CUENTAS_CONTABLES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblCuentasContables.TBL_CUENTAS_CONTABLES.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblCuentasContables.TBL_CUENTAS_CONTABLES.ID_CUENTA_MADRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TblCuentasContables.TBL_CUENTAS_CONTABLES.IMPUTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdCuentaMadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getImputable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesRecord value3(Integer value) {
        setIdCuentaMadre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesRecord value4(Boolean value) {
        setImputable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblCuentasContablesRecord values(Integer value1, String value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblCuentasContablesRecord
     */
    public TblCuentasContablesRecord() {
        super(TblCuentasContables.TBL_CUENTAS_CONTABLES);
    }

    /**
     * Create a detached, initialised TblCuentasContablesRecord
     */
    public TblCuentasContablesRecord(Integer id, String descripcion, Integer idCuentaMadre, Boolean imputable) {
        super(TblCuentasContables.TBL_CUENTAS_CONTABLES);

        set(0, id);
        set(1, descripcion);
        set(2, idCuentaMadre);
        set(3, imputable);
    }
}
