/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblContribuyentes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblContribuyentesRecord extends UpdatableRecordImpl<TblContribuyentesRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -35907221;

    /**
     * Setter for <code>MG.TBL_CONTRIBUYENTES.RUC_SIN_DV</code>.
     */
    public void setRucSinDv(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_CONTRIBUYENTES.RUC_SIN_DV</code>.
     */
    public String getRucSinDv() {
        return (String) get(0);
    }

    /**
     * Setter for <code>MG.TBL_CONTRIBUYENTES.DV</code>.
     */
    public void setDv(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_CONTRIBUYENTES.DV</code>.
     */
    public String getDv() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_CONTRIBUYENTES.RAZON_SOCIAL</code>.
     */
    public void setRazonSocial(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_CONTRIBUYENTES.RAZON_SOCIAL</code>.
     */
    public String getRazonSocial() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TblContribuyentes.TBL_CONTRIBUYENTES.RUC_SIN_DV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblContribuyentes.TBL_CONTRIBUYENTES.DV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblContribuyentes.TBL_CONTRIBUYENTES.RAZON_SOCIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRucSinDv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblContribuyentesRecord value1(String value) {
        setRucSinDv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblContribuyentesRecord value2(String value) {
        setDv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblContribuyentesRecord value3(String value) {
        setRazonSocial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblContribuyentesRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblContribuyentesRecord
     */
    public TblContribuyentesRecord() {
        super(TblContribuyentes.TBL_CONTRIBUYENTES);
    }

    /**
     * Create a detached, initialised TblContribuyentesRecord
     */
    public TblContribuyentesRecord(String rucSinDv, String dv, String razonSocial) {
        super(TblContribuyentes.TBL_CONTRIBUYENTES);

        set(0, rucSinDv);
        set(1, dv);
        set(2, razonSocial);
    }
}
