/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEventoDetalle;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventoDetalleRecord extends UpdatableRecordImpl<TblEventoDetalleRecord> implements Record9<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 515249706;

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.OBSERVACION</code>.
     */
    public void setObservacion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.OBSERVACION</code>.
     */
    public String getObservacion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID_ENTIDAD</code>.
     */
    public void setIdEntidad(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID_ENTIDAD</code>.
     */
    public Integer getIdEntidad() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID_EVENTO</code>.
     */
    public void setIdEvento(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID_EVENTO</code>.
     */
    public Integer getIdEvento() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID_CATEGORIA_ARTICULO</code>.
     */
    public void setIdCategoriaArticulo(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID_CATEGORIA_ARTICULO</code>.
     */
    public Integer getIdCategoriaArticulo() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID_FORMA_DE_PAGO_PREFERIDA</code>.
     */
    public void setIdFormaDePagoPreferida(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID_FORMA_DE_PAGO_PREFERIDA</code>.
     */
    public Integer getIdFormaDePagoPreferida() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.OBSERVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID_ENTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID_EVENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID_CATEGORIA_ARTICULO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID_FORMA_DE_PAGO_PREFERIDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblEventoDetalle.TBL_EVENTO_DETALLE.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdEntidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdEvento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdCategoriaArticulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdFormaDePagoPreferida();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value3(String value) {
        setObservacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value4(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value5(Integer value) {
        setIdEntidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value6(Integer value) {
        setIdEvento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value7(Integer value) {
        setIdCategoriaArticulo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value8(Integer value) {
        setIdFormaDePagoPreferida(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord value9(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleRecord values(Integer value1, Timestamp value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEventoDetalleRecord
     */
    public TblEventoDetalleRecord() {
        super(TblEventoDetalle.TBL_EVENTO_DETALLE);
    }

    /**
     * Create a detached, initialised TblEventoDetalleRecord
     */
    public TblEventoDetalleRecord(Integer id, Timestamp fechahora, String observacion, Integer monto, Integer idEntidad, Integer idEvento, Integer idCategoriaArticulo, Integer idFormaDePagoPreferida, Integer idUser) {
        super(TblEventoDetalle.TBL_EVENTO_DETALLE);

        set(0, id);
        set(1, fechahora);
        set(2, observacion);
        set(3, monto);
        set(4, idEntidad);
        set(5, idEvento);
        set(6, idCategoriaArticulo);
        set(7, idFormaDePagoPreferida);
        set(8, idUser);
    }
}
