/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEventoDetalleAsientos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventoDetalleAsientosRecord extends TableRecordImpl<TblEventoDetalleAsientosRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1757109811;

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE_ASIENTOS.ID_EVENTO_DETALLE</code>.
     */
    public void setIdEventoDetalle(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE_ASIENTOS.ID_EVENTO_DETALLE</code>.
     */
    public Integer getIdEventoDetalle() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_DETALLE_ASIENTOS.ID_ASIENTO</code>.
     */
    public void setIdAsiento(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_DETALLE_ASIENTOS.ID_ASIENTO</code>.
     */
    public Integer getIdAsiento() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblEventoDetalleAsientos.TBL_EVENTO_DETALLE_ASIENTOS.ID_EVENTO_DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblEventoDetalleAsientos.TBL_EVENTO_DETALLE_ASIENTOS.ID_ASIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdEventoDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdAsiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleAsientosRecord value1(Integer value) {
        setIdEventoDetalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleAsientosRecord value2(Integer value) {
        setIdAsiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoDetalleAsientosRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEventoDetalleAsientosRecord
     */
    public TblEventoDetalleAsientosRecord() {
        super(TblEventoDetalleAsientos.TBL_EVENTO_DETALLE_ASIENTOS);
    }

    /**
     * Create a detached, initialised TblEventoDetalleAsientosRecord
     */
    public TblEventoDetalleAsientosRecord(Integer idEventoDetalle, Integer idAsiento) {
        super(TblEventoDetalleAsientos.TBL_EVENTO_DETALLE_ASIENTOS);

        set(0, idEventoDetalle);
        set(1, idAsiento);
    }
}
