/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEventos;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventosRecord extends UpdatableRecordImpl<TblEventosRecord> implements Record8<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -153931246;

    /**
     * Setter for <code>MG.TBL_EVENTOS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.FECHA</code>.
     */
    public void setFecha(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.FECHA</code>.
     */
    public Timestamp getFecha() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.PORCENTAJE_APORTE</code>.
     */
    public void setPorcentajeAporte(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.PORCENTAJE_APORTE</code>.
     */
    public Integer getPorcentajeAporte() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.ID_EVENTO_TIPO</code>.
     */
    public void setIdEventoTipo(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.ID_EVENTO_TIPO</code>.
     */
    public Integer getIdEventoTipo() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.ID_GRUPO</code>.
     */
    public void setIdGrupo(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.ID_GRUPO</code>.
     */
    public Integer getIdGrupo() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_EVENTOS.ID_CENTRO_DE_COSTO</code>.
     */
    public void setIdCentroDeCosto(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTOS.ID_CENTRO_DE_COSTO</code>.
     */
    public Integer getIdCentroDeCosto() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblEventos.TBL_EVENTOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblEventos.TBL_EVENTOS.FECHA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblEventos.TBL_EVENTOS.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblEventos.TBL_EVENTOS.PORCENTAJE_APORTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblEventos.TBL_EVENTOS.ID_EVENTO_TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblEventos.TBL_EVENTOS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblEventos.TBL_EVENTOS.ID_GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblEventos.TBL_EVENTOS.ID_CENTRO_DE_COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFecha();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPorcentajeAporte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdEventoTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdCentroDeCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value2(Timestamp value) {
        setFecha(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value4(Integer value) {
        setPorcentajeAporte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value5(Integer value) {
        setIdEventoTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value6(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value7(Integer value) {
        setIdGrupo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord value8(Integer value) {
        setIdCentroDeCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventosRecord values(Integer value1, Timestamp value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEventosRecord
     */
    public TblEventosRecord() {
        super(TblEventos.TBL_EVENTOS);
    }

    /**
     * Create a detached, initialised TblEventosRecord
     */
    public TblEventosRecord(Integer id, Timestamp fecha, String descripcion, Integer porcentajeAporte, Integer idEventoTipo, Integer idUser, Integer idGrupo, Integer idCentroDeCosto) {
        super(TblEventos.TBL_EVENTOS);

        set(0, id);
        set(1, fecha);
        set(2, descripcion);
        set(3, porcentajeAporte);
        set(4, idEventoTipo);
        set(5, idUser);
        set(6, idGrupo);
        set(7, idCentroDeCosto);
    }
}
