/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEventoCuotas;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEventoCuotasRecord extends UpdatableRecordImpl<TblEventoCuotasRecord> implements Record6<Integer, Timestamp, Timestamp, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 928611162;

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.ID_EVENTO</code>.
     */
    public void setIdEvento(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.ID_EVENTO</code>.
     */
    public Integer getIdEvento() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_1</code>.
     */
    public void setFecha_1(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_1</code>.
     */
    public Timestamp getFecha_1() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_2</code>.
     */
    public void setFecha_2(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_2</code>.
     */
    public Timestamp getFecha_2() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_3</code>.
     */
    public void setFecha_3(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_3</code>.
     */
    public Timestamp getFecha_3() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_4</code>.
     */
    public void setFecha_4(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.FECHA_4</code>.
     */
    public Timestamp getFecha_4() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>MG.TBL_EVENTO_CUOTAS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_EVENTO_CUOTAS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.ID_EVENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.FECHA_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.FECHA_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.FECHA_3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.FECHA_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblEventoCuotas.TBL_EVENTO_CUOTAS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdEvento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFecha_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFecha_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFecha_3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFecha_4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value1(Integer value) {
        setIdEvento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value2(Timestamp value) {
        setFecha_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value3(Timestamp value) {
        setFecha_2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value4(Timestamp value) {
        setFecha_3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value5(Timestamp value) {
        setFecha_4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord value6(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEventoCuotasRecord values(Integer value1, Timestamp value2, Timestamp value3, Timestamp value4, Timestamp value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEventoCuotasRecord
     */
    public TblEventoCuotasRecord() {
        super(TblEventoCuotas.TBL_EVENTO_CUOTAS);
    }

    /**
     * Create a detached, initialised TblEventoCuotasRecord
     */
    public TblEventoCuotasRecord(Integer idEvento, Timestamp fecha_1, Timestamp fecha_2, Timestamp fecha_3, Timestamp fecha_4, Integer idUser) {
        super(TblEventoCuotas.TBL_EVENTO_CUOTAS);

        set(0, idEvento);
        set(1, fecha_1);
        set(2, fecha_2);
        set(3, fecha_3);
        set(4, fecha_4);
        set(5, idUser);
    }
}
