/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEntidades;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEntidadesRecord extends UpdatableRecordImpl<TblEntidadesRecord> {

    private static final long serialVersionUID = -141373162;

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.NOMBRES</code>.
     */
    public void setNombres(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.NOMBRES</code>.
     */
    public String getNombres() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.APELLIDOS</code>.
     */
    public void setApellidos(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.APELLIDOS</code>.
     */
    public String getApellidos() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.RAZON_SOCIAL</code>.
     */
    public void setRazonSocial(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.RAZON_SOCIAL</code>.
     */
    public String getRazonSocial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.RUC_SIN_DV</code>.
     */
    public void setRucSinDv(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.RUC_SIN_DV</code>.
     */
    public String getRucSinDv() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.CTACTE</code>.
     */
    public void setCtacte(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.CTACTE</code>.
     */
    public Integer getCtacte() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.DOMICILIO</code>.
     */
    public void setDomicilio(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.DOMICILIO</code>.
     */
    public String getDomicilio() {
        return (String) get(6);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.BOX</code>.
     */
    public void setBox(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.BOX</code>.
     */
    public Integer getBox() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.IS_MIEMBRO_ACTIVO</code>.
     */
    public void setIsMiembroActivo(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.IS_MIEMBRO_ACTIVO</code>.
     */
    public Boolean getIsMiembroActivo() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_FORMA_DE_PAGO_PREFERIDA</code>.
     */
    public void setIdFormaDePagoPreferida(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_FORMA_DE_PAGO_PREFERIDA</code>.
     */
    public Integer getIdFormaDePagoPreferida() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.APORTE_MENSUAL</code>.
     */
    public void setAporteMensual(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.APORTE_MENSUAL</code>.
     */
    public Integer getAporteMensual() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_ENTIDAD_PAGANTE_APORTES</code>.
     */
    public void setIdEntidadPaganteAportes(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_ENTIDAD_PAGANTE_APORTES</code>.
     */
    public Integer getIdEntidadPaganteAportes() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.FECHA_NACIMIENTO</code>.
     */
    public void setFechaNacimiento(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.FECHA_NACIMIENTO</code>.
     */
    public Timestamp getFechaNacimiento() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.FECHA_BAUTISMO</code>.
     */
    public void setFechaBautismo(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.FECHA_BAUTISMO</code>.
     */
    public Timestamp getFechaBautismo() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.FECHA_ENTRADA_CONGREGACION</code>.
     */
    public void setFechaEntradaCongregacion(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.FECHA_ENTRADA_CONGREGACION</code>.
     */
    public Timestamp getFechaEntradaCongregacion() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.FECHA_SALIDA_CONGREGACION</code>.
     */
    public void setFechaSalidaCongregacion(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.FECHA_SALIDA_CONGREGACION</code>.
     */
    public Timestamp getFechaSalidaCongregacion() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.FECHA_DEFUNCION</code>.
     */
    public void setFechaDefuncion(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.FECHA_DEFUNCION</code>.
     */
    public Timestamp getFechaDefuncion() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_AREA_SERVICIO_EN_IGLESIA</code>.
     */
    public void setIdAreaServicioEnIglesia(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_AREA_SERVICIO_EN_IGLESIA</code>.
     */
    public Integer getIdAreaServicioEnIglesia() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_MIEMBROS_CATEGORIA_DE_PAGO</code>.
     */
    public void setIdMiembrosCategoriaDePago(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_MIEMBROS_CATEGORIA_DE_PAGO</code>.
     */
    public Integer getIdMiembrosCategoriaDePago() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_MIEMBROS_ALERGIA</code>.
     */
    public void setIdMiembrosAlergia(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_MIEMBROS_ALERGIA</code>.
     */
    public Integer getIdMiembrosAlergia() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.APORTE_SALDO_ANTERIOR</code>.
     */
    public void setAporteSaldoAnterior(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.APORTE_SALDO_ANTERIOR</code>.
     */
    public Long getAporteSaldoAnterior() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.MES_INICIO_APORTE</code>.
     */
    public void setMesInicioAporte(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.MES_INICIO_APORTE</code>.
     */
    public Integer getMesInicioAporte() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.MES_FIN_APORTE</code>.
     */
    public void setMesFinAporte(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.MES_FIN_APORTE</code>.
     */
    public Integer getMesFinAporte() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES.CANTIDAD_DE_DEPENDIENTES_APORTANTES</code>.
     */
    public void setCantidadDeDependientesAportantes(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES.CANTIDAD_DE_DEPENDIENTES_APORTANTES</code>.
     */
    public Integer getCantidadDeDependientesAportantes() {
        return (Integer) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEntidadesRecord
     */
    public TblEntidadesRecord() {
        super(TblEntidades.TBL_ENTIDADES);
    }

    /**
     * Create a detached, initialised TblEntidadesRecord
     */
    public TblEntidadesRecord(Integer id, String nombres, String apellidos, String razonSocial, String rucSinDv, Integer ctacte, String domicilio, Integer box, Boolean isMiembroActivo, Integer idFormaDePagoPreferida, Integer aporteMensual, Integer idEntidadPaganteAportes, Timestamp fechaNacimiento, Timestamp fechaBautismo, Timestamp fechaEntradaCongregacion, Timestamp fechaSalidaCongregacion, Timestamp fechaDefuncion, Integer idAreaServicioEnIglesia, Integer idMiembrosCategoriaDePago, Integer idMiembrosAlergia, Integer idUser, Long aporteSaldoAnterior, Integer mesInicioAporte, Integer mesFinAporte, Integer cantidadDeDependientesAportantes) {
        super(TblEntidades.TBL_ENTIDADES);

        set(0, id);
        set(1, nombres);
        set(2, apellidos);
        set(3, razonSocial);
        set(4, rucSinDv);
        set(5, ctacte);
        set(6, domicilio);
        set(7, box);
        set(8, isMiembroActivo);
        set(9, idFormaDePagoPreferida);
        set(10, aporteMensual);
        set(11, idEntidadPaganteAportes);
        set(12, fechaNacimiento);
        set(13, fechaBautismo);
        set(14, fechaEntradaCongregacion);
        set(15, fechaSalidaCongregacion);
        set(16, fechaDefuncion);
        set(17, idAreaServicioEnIglesia);
        set(18, idMiembrosCategoriaDePago);
        set(19, idMiembrosAlergia);
        set(20, idUser);
        set(21, aporteSaldoAnterior);
        set(22, mesInicioAporte);
        set(23, mesFinAporte);
        set(24, cantidadDeDependientesAportantes);
    }
}
