/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblEntidadesHistoricoCategorias;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEntidadesHistoricoCategoriasRecord extends UpdatableRecordImpl<TblEntidadesHistoricoCategoriasRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 862342938;

    /**
     * Setter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_ENTIDAD</code>.
     */
    public void setIdEntidad(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_ENTIDAD</code>.
     */
    public Integer getIdEntidad() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ANO_MES</code>.
     */
    public void setAnoMes(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ANO_MES</code>.
     */
    public Integer getAnoMes() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_CATEGORIA_DE_PAGO</code>.
     */
    public void setIdCategoriaDePago(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_CATEGORIA_DE_PAGO</code>.
     */
    public Integer getIdCategoriaDePago() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_ENTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ANO_MES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS.ID_CATEGORIA_DE_PAGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdEntidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAnoMes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdCategoriaDePago();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategoriasRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategoriasRecord value2(Integer value) {
        setIdEntidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategoriasRecord value3(Integer value) {
        setAnoMes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategoriasRecord value4(Integer value) {
        setIdCategoriaDePago(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEntidadesHistoricoCategoriasRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblEntidadesHistoricoCategoriasRecord
     */
    public TblEntidadesHistoricoCategoriasRecord() {
        super(TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS);
    }

    /**
     * Create a detached, initialised TblEntidadesHistoricoCategoriasRecord
     */
    public TblEntidadesHistoricoCategoriasRecord(Integer id, Integer idEntidad, Integer anoMes, Integer idCategoriaDePago) {
        super(TblEntidadesHistoricoCategorias.TBL_ENTIDADES_HISTORICO_CATEGORIAS);

        set(0, id);
        set(1, idEntidad);
        set(2, anoMes);
        set(3, idCategoriaDePago);
    }
}
