/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblFacturasCompra;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblFacturasCompraRecord extends UpdatableRecordImpl<TblFacturasCompraRecord> implements Record17<Integer, String, String, Timestamp, Boolean, Timestamp, Integer, Timestamp, String, String, Integer, Integer, Integer, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -1037679574;

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.NRO</code>.
     */
    public void setNro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.NRO</code>.
     */
    public String getNro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.NRO_TIMBRADO</code>.
     */
    public void setNroTimbrado(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.NRO_TIMBRADO</code>.
     */
    public String getNroTimbrado() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.VENCIMIENTO_TIMBRADO</code>.
     */
    public void setVencimientoTimbrado(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.VENCIMIENTO_TIMBRADO</code>.
     */
    public Timestamp getVencimientoTimbrado() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.CONDICION_CONTADO</code>.
     */
    public void setCondicionContado(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.CONDICION_CONTADO</code>.
     */
    public Boolean getCondicionContado() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.FECHA_VENCIMIENTO_CREDITO</code>.
     */
    public void setFechaVencimientoCredito(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.FECHA_VENCIMIENTO_CREDITO</code>.
     */
    public Timestamp getFechaVencimientoCredito() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.CUOTAS_CREDITO</code>.
     */
    public void setCuotasCredito(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.CUOTAS_CREDITO</code>.
     */
    public Integer getCuotasCredito() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.RAZON_SOCIAL</code>.
     */
    public void setRazonSocial(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.RAZON_SOCIAL</code>.
     */
    public String getRazonSocial() {
        return (String) get(8);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.RUC</code>.
     */
    public void setRuc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.RUC</code>.
     */
    public String getRuc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_EXENTAS</code>.
     */
    public void setMontoExentas(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_EXENTAS</code>.
     */
    public Integer getMontoExentas() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_IVA5</code>.
     */
    public void setMontoIva5(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_IVA5</code>.
     */
    public Integer getMontoIva5() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_IVA10</code>.
     */
    public void setMontoIva10(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.MONTO_IVA10</code>.
     */
    public Integer getMontoIva10() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.IVA5</code>.
     */
    public void setIva5(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.IVA5</code>.
     */
    public Integer getIva5() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.IVA10</code>.
     */
    public void setIva10(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.IVA10</code>.
     */
    public Integer getIva10() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.OBSERVACION</code>.
     */
    public void setObservacion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.OBSERVACION</code>.
     */
    public String getObservacion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>MG.TBL_FACTURAS_COMPRA.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>MG.TBL_FACTURAS_COMPRA.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, Timestamp, Boolean, Timestamp, Integer, Timestamp, String, String, Integer, Integer, Integer, Integer, Integer, String, Integer> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, Timestamp, Boolean, Timestamp, Integer, Timestamp, String, String, Integer, Integer, Integer, Integer, Integer, String, Integer> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.NRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.NRO_TIMBRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.VENCIMIENTO_TIMBRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.CONDICION_CONTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.FECHA_VENCIMIENTO_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.CUOTAS_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.RAZON_SOCIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.RUC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.MONTO_EXENTAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.MONTO_IVA5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.MONTO_IVA10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.IVA5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.IVA10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.OBSERVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return TblFacturasCompra.TBL_FACTURAS_COMPRA.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNroTimbrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getVencimientoTimbrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getCondicionContado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFechaVencimientoCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCuotasCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRuc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMontoExentas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getMontoIva5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getMontoIva10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getIva5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getIva10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value2(String value) {
        setNro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value3(String value) {
        setNroTimbrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value4(Timestamp value) {
        setVencimientoTimbrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value5(Boolean value) {
        setCondicionContado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value6(Timestamp value) {
        setFechaVencimientoCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value7(Integer value) {
        setCuotasCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value8(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value9(String value) {
        setRazonSocial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value10(String value) {
        setRuc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value11(Integer value) {
        setMontoExentas(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value12(Integer value) {
        setMontoIva5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value13(Integer value) {
        setMontoIva10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value14(Integer value) {
        setIva5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value15(Integer value) {
        setIva10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value16(String value) {
        setObservacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord value17(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblFacturasCompraRecord values(Integer value1, String value2, String value3, Timestamp value4, Boolean value5, Timestamp value6, Integer value7, Timestamp value8, String value9, String value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, String value16, Integer value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblFacturasCompraRecord
     */
    public TblFacturasCompraRecord() {
        super(TblFacturasCompra.TBL_FACTURAS_COMPRA);
    }

    /**
     * Create a detached, initialised TblFacturasCompraRecord
     */
    public TblFacturasCompraRecord(Integer id, String nro, String nroTimbrado, Timestamp vencimientoTimbrado, Boolean condicionContado, Timestamp fechaVencimientoCredito, Integer cuotasCredito, Timestamp fechahora, String razonSocial, String ruc, Integer montoExentas, Integer montoIva5, Integer montoIva10, Integer iva5, Integer iva10, String observacion, Integer idUser) {
        super(TblFacturasCompra.TBL_FACTURAS_COMPRA);

        set(0, id);
        set(1, nro);
        set(2, nroTimbrado);
        set(3, vencimientoTimbrado);
        set(4, condicionContado);
        set(5, fechaVencimientoCredito);
        set(6, cuotasCredito);
        set(7, fechahora);
        set(8, razonSocial);
        set(9, ruc);
        set(10, montoExentas);
        set(11, montoIva5);
        set(12, montoIva10);
        set(13, iva5);
        set(14, iva10);
        set(15, observacion);
        set(16, idUser);
    }
}
