/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblGrupos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblGruposRecord extends UpdatableRecordImpl<TblGruposRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -623216067;

    /**
     * Setter for <code>MG.TBL_GRUPOS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_GRUPOS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_GRUPOS.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_GRUPOS.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblGrupos.TBL_GRUPOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblGrupos.TBL_GRUPOS.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblGruposRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblGruposRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblGruposRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblGruposRecord
     */
    public TblGruposRecord() {
        super(TblGrupos.TBL_GRUPOS);
    }

    /**
     * Create a detached, initialised TblGruposRecord
     */
    public TblGruposRecord(Integer id, String descripcion) {
        super(TblGrupos.TBL_GRUPOS);

        set(0, id);
        set(1, descripcion);
    }
}
