/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblIglesia;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblIglesiaRecord extends UpdatableRecordImpl<TblIglesiaRecord> implements Record6<Integer, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = -1143321745;

    /**
     * Setter for <code>MG.TBL_IGLESIA.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_IGLESIA.NOMBRE</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.NOMBRE</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_IGLESIA.RUC_SIN_DV</code>.
     */
    public void setRucSinDv(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.RUC_SIN_DV</code>.
     */
    public String getRucSinDv() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_IGLESIA.CTACTE</code>.
     */
    public void setCtacte(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.CTACTE</code>.
     */
    public Integer getCtacte() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_IGLESIA.DOMICILIO</code>.
     */
    public void setDomicilio(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.DOMICILIO</code>.
     */
    public String getDomicilio() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TBL_IGLESIA.BOX</code>.
     */
    public void setBox(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_IGLESIA.BOX</code>.
     */
    public Integer getBox() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblIglesia.TBL_IGLESIA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblIglesia.TBL_IGLESIA.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblIglesia.TBL_IGLESIA.RUC_SIN_DV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblIglesia.TBL_IGLESIA.CTACTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblIglesia.TBL_IGLESIA.DOMICILIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblIglesia.TBL_IGLESIA.BOX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRucSinDv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCtacte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBox();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value3(String value) {
        setRucSinDv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value4(Integer value) {
        setCtacte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value5(String value) {
        setDomicilio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord value6(Integer value) {
        setBox(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblIglesiaRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblIglesiaRecord
     */
    public TblIglesiaRecord() {
        super(TblIglesia.TBL_IGLESIA);
    }

    /**
     * Create a detached, initialised TblIglesiaRecord
     */
    public TblIglesiaRecord(Integer id, String nombre, String rucSinDv, Integer ctacte, String domicilio, Integer box) {
        super(TblIglesia.TBL_IGLESIA);

        set(0, id);
        set(1, nombre);
        set(2, rucSinDv);
        set(3, ctacte);
        set(4, domicilio);
        set(5, box);
    }
}
