/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblMiembrosRelacionesRoles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosRelacionesRolesRecord extends UpdatableRecordImpl<TblMiembrosRelacionesRolesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -576947889;

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES_ROLES.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblMiembrosRelacionesRoles.TBL_MIEMBROS_RELACIONES_ROLES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblMiembrosRelacionesRoles.TBL_MIEMBROS_RELACIONES_ROLES.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRolesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRolesRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRolesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblMiembrosRelacionesRolesRecord
     */
    public TblMiembrosRelacionesRolesRecord() {
        super(TblMiembrosRelacionesRoles.TBL_MIEMBROS_RELACIONES_ROLES);
    }

    /**
     * Create a detached, initialised TblMiembrosRelacionesRolesRecord
     */
    public TblMiembrosRelacionesRolesRecord(Integer id, String descripcion) {
        super(TblMiembrosRelacionesRoles.TBL_MIEMBROS_RELACIONES_ROLES);

        set(0, id);
        set(1, descripcion);
    }
}
