/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblMiembrosCategoriasDePago;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosCategoriasDePagoRecord extends UpdatableRecordImpl<TblMiembrosCategoriasDePagoRecord> implements Record3<Integer, String, Boolean> {

    private static final long serialVersionUID = -1438848611;

    /**
     * Setter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ES_ACTIVACION</code>.
     */
    public void setEsActivacion(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ES_ACTIVACION</code>.
     */
    public Boolean getEsActivacion() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblMiembrosCategoriasDePago.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblMiembrosCategoriasDePago.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return TblMiembrosCategoriasDePago.TBL_MIEMBROS_CATEGORIAS_DE_PAGO.ES_ACTIVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getEsActivacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosCategoriasDePagoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosCategoriasDePagoRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosCategoriasDePagoRecord value3(Boolean value) {
        setEsActivacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosCategoriasDePagoRecord values(Integer value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblMiembrosCategoriasDePagoRecord
     */
    public TblMiembrosCategoriasDePagoRecord() {
        super(TblMiembrosCategoriasDePago.TBL_MIEMBROS_CATEGORIAS_DE_PAGO);
    }

    /**
     * Create a detached, initialised TblMiembrosCategoriasDePagoRecord
     */
    public TblMiembrosCategoriasDePagoRecord(Integer id, String descripcion, Boolean esActivacion) {
        super(TblMiembrosCategoriasDePago.TBL_MIEMBROS_CATEGORIAS_DE_PAGO);

        set(0, id);
        set(1, descripcion);
        set(2, esActivacion);
    }
}
