/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblMiembrosFamilias;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosFamiliasRecord extends UpdatableRecordImpl<TblMiembrosFamiliasRecord> implements Record3<Integer, String, byte[]> {

    private static final long serialVersionUID = -1349274105;

    /**
     * Setter for <code>MG.TBL_MIEMBROS_FAMILIAS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_FAMILIAS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_FAMILIAS.DESCRIPCION</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_FAMILIAS.DESCRIPCION</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_FAMILIAS.FOTO</code>.
     */
    public void setFoto(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_FAMILIAS.FOTO</code>.
     */
    public byte[] getFoto() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, byte[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblMiembrosFamilias.TBL_MIEMBROS_FAMILIAS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblMiembrosFamilias.TBL_MIEMBROS_FAMILIAS.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return TblMiembrosFamilias.TBL_MIEMBROS_FAMILIAS.FOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getFoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosFamiliasRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosFamiliasRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosFamiliasRecord value3(byte... value) {
        setFoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosFamiliasRecord values(Integer value1, String value2, byte[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblMiembrosFamiliasRecord
     */
    public TblMiembrosFamiliasRecord() {
        super(TblMiembrosFamilias.TBL_MIEMBROS_FAMILIAS);
    }

    /**
     * Create a detached, initialised TblMiembrosFamiliasRecord
     */
    public TblMiembrosFamiliasRecord(Integer id, String descripcion, byte[] foto) {
        super(TblMiembrosFamilias.TBL_MIEMBROS_FAMILIAS);

        set(0, id);
        set(1, descripcion);
        set(2, foto);
    }
}
