/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblMiembrosRelaciones;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblMiembrosRelacionesRecord extends UpdatableRecordImpl<TblMiembrosRelacionesRecord> implements Record10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = -218830089;

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_FAMILIA</code>.
     */
    public void setIdMiembrosFamilia(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_FAMILIA</code>.
     */
    public Integer getIdMiembrosFamilia() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_1</code>.
     */
    public void setIdEntidad_1(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_1</code>.
     */
    public Integer getIdEntidad_1() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_2</code>.
     */
    public void setIdEntidad_2(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_2</code>.
     */
    public Integer getIdEntidad_2() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_TIPO</code>.
     */
    public void setIdMiembrosRelacionesTipo(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_TIPO</code>.
     */
    public Integer getIdMiembrosRelacionesTipo() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_1</code>.
     */
    public void setIdMiembrosRelacionesRol_1(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_1</code>.
     */
    public Integer getIdMiembrosRelacionesRol_1() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_2</code>.
     */
    public void setIdMiembrosRelacionesRol_2(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_2</code>.
     */
    public Integer getIdMiembrosRelacionesRol_2() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_INICIO</code>.
     */
    public void setFechaInicio(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_INICIO</code>.
     */
    public Timestamp getFechaInicio() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_FIN</code>.
     */
    public void setFechaFin(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.FECHA_FIN</code>.
     */
    public Timestamp getFechaFin() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_MIEMBROS_RELACIONES.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_FAMILIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_ENTIDAD_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_MIEMBROS_RELACIONES_ROL_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.FECHA_INICIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.FECHA_FIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdMiembrosFamilia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdEntidad_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIdEntidad_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIdMiembrosRelacionesTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdMiembrosRelacionesRol_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdMiembrosRelacionesRol_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value2(Integer value) {
        setIdMiembrosFamilia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value3(Integer value) {
        setIdEntidad_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value4(Integer value) {
        setIdEntidad_2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value5(Integer value) {
        setIdMiembrosRelacionesTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value6(Integer value) {
        setIdMiembrosRelacionesRol_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value7(Integer value) {
        setIdMiembrosRelacionesRol_2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value8(Timestamp value) {
        setFechaInicio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value9(Timestamp value) {
        setFechaFin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord value10(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblMiembrosRelacionesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblMiembrosRelacionesRecord
     */
    public TblMiembrosRelacionesRecord() {
        super(TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES);
    }

    /**
     * Create a detached, initialised TblMiembrosRelacionesRecord
     */
    public TblMiembrosRelacionesRecord(Integer id, Integer idMiembrosFamilia, Integer idEntidad_1, Integer idEntidad_2, Integer idMiembrosRelacionesTipo, Integer idMiembrosRelacionesRol_1, Integer idMiembrosRelacionesRol_2, Timestamp fechaInicio, Timestamp fechaFin, Integer idUser) {
        super(TblMiembrosRelaciones.TBL_MIEMBROS_RELACIONES);

        set(0, id);
        set(1, idMiembrosFamilia);
        set(2, idEntidad_1);
        set(3, idEntidad_2);
        set(4, idMiembrosRelacionesTipo);
        set(5, idMiembrosRelacionesRol_1);
        set(6, idMiembrosRelacionesRol_2);
        set(7, fechaInicio);
        set(8, fechaFin);
        set(9, idUser);
    }
}
