/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblNotasDeCredito;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNotasDeCreditoRecord extends UpdatableRecordImpl<TblNotasDeCreditoRecord> implements Record7<Integer, String, Integer, Timestamp, Integer, Boolean, Integer> {

    private static final long serialVersionUID = -250896164;

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.NRO</code>.
     */
    public void setNro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.NRO</code>.
     */
    public String getNro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.ID_TIMBRADO</code>.
     */
    public void setIdTimbrado(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.ID_TIMBRADO</code>.
     */
    public Integer getIdTimbrado() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.NRO_FACTURA</code>.
     */
    public void setNroFactura(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.NRO_FACTURA</code>.
     */
    public Integer getNroFactura() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.ANULADO</code>.
     */
    public void setAnulado(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.ANULADO</code>.
     */
    public Boolean getAnulado() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Timestamp, Integer, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Timestamp, Integer, Boolean, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.NRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.ID_TIMBRADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.NRO_FACTURA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.ANULADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblNotasDeCredito.TBL_NOTAS_DE_CREDITO.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIdTimbrado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNroFactura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getAnulado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value2(String value) {
        setNro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value3(Integer value) {
        setIdTimbrado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value4(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value5(Integer value) {
        setNroFactura(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value6(Boolean value) {
        setAnulado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord value7(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Integer value5, Boolean value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblNotasDeCreditoRecord
     */
    public TblNotasDeCreditoRecord() {
        super(TblNotasDeCredito.TBL_NOTAS_DE_CREDITO);
    }

    /**
     * Create a detached, initialised TblNotasDeCreditoRecord
     */
    public TblNotasDeCreditoRecord(Integer id, String nro, Integer idTimbrado, Timestamp fechahora, Integer nroFactura, Boolean anulado, Integer idUser) {
        super(TblNotasDeCredito.TBL_NOTAS_DE_CREDITO);

        set(0, id);
        set(1, nro);
        set(2, idTimbrado);
        set(3, fechahora);
        set(4, nroFactura);
        set(5, anulado);
        set(6, idUser);
    }
}
