/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblNotasDeCreditoAsientos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblNotasDeCreditoAsientosRecord extends TableRecordImpl<TblNotasDeCreditoAsientosRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1553983987;

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_NOTA_DE_CREDITO</code>.
     */
    public void setIdNotaDeCredito(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_NOTA_DE_CREDITO</code>.
     */
    public Integer getIdNotaDeCredito() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_ASIENTO</code>.
     */
    public void setIdAsiento(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_ASIENTO</code>.
     */
    public Integer getIdAsiento() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblNotasDeCreditoAsientos.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_NOTA_DE_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblNotasDeCreditoAsientos.TBL_NOTAS_DE_CREDITO_ASIENTOS.ID_ASIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdNotaDeCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdAsiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoAsientosRecord value1(Integer value) {
        setIdNotaDeCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoAsientosRecord value2(Integer value) {
        setIdAsiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblNotasDeCreditoAsientosRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblNotasDeCreditoAsientosRecord
     */
    public TblNotasDeCreditoAsientosRecord() {
        super(TblNotasDeCreditoAsientos.TBL_NOTAS_DE_CREDITO_ASIENTOS);
    }

    /**
     * Create a detached, initialised TblNotasDeCreditoAsientosRecord
     */
    public TblNotasDeCreditoAsientosRecord(Integer idNotaDeCredito, Integer idAsiento) {
        super(TblNotasDeCreditoAsientos.TBL_NOTAS_DE_CREDITO_ASIENTOS);

        set(0, idNotaDeCredito);
        set(1, idAsiento);
    }
}
