/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblRecibosCompraFacturasCompra;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosCompraFacturasCompraRecord extends UpdatableRecordImpl<TblRecibosCompraFacturasCompraRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 306968519;

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_RECIBO</code>.
     */
    public void setIdRecibo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_RECIBO</code>.
     */
    public Integer getIdRecibo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_FACTURA_COMPRA</code>.
     */
    public void setIdFacturaCompra(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_FACTURA_COMPRA</code>.
     */
    public Integer getIdFacturaCompra() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblRecibosCompraFacturasCompra.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_RECIBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblRecibosCompraFacturasCompra.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.ID_FACTURA_COMPRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TblRecibosCompraFacturasCompra.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdRecibo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdFacturaCompra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraFacturasCompraRecord value1(Integer value) {
        setIdRecibo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraFacturasCompraRecord value2(Integer value) {
        setIdFacturaCompra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraFacturasCompraRecord value3(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraFacturasCompraRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblRecibosCompraFacturasCompraRecord
     */
    public TblRecibosCompraFacturasCompraRecord() {
        super(TblRecibosCompraFacturasCompra.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA);
    }

    /**
     * Create a detached, initialised TblRecibosCompraFacturasCompraRecord
     */
    public TblRecibosCompraFacturasCompraRecord(Integer idRecibo, Integer idFacturaCompra, Integer monto) {
        super(TblRecibosCompraFacturasCompra.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA);

        set(0, idRecibo);
        set(1, idFacturaCompra);
        set(2, monto);
    }
}
