/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblRolesUsers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRolesUsersRecord extends UpdatableRecordImpl<TblRolesUsersRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 863766668;

    /**
     * Setter for <code>MG.TBL_ROLES_USERS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_ROLES_USERS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_ROLES_USERS.ID_ROLE</code>.
     */
    public void setIdRole(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_ROLES_USERS.ID_ROLE</code>.
     */
    public Integer getIdRole() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblRolesUsers.TBL_ROLES_USERS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblRolesUsers.TBL_ROLES_USERS.ID_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRolesUsersRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRolesUsersRecord value2(Integer value) {
        setIdRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRolesUsersRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblRolesUsersRecord
     */
    public TblRolesUsersRecord() {
        super(TblRolesUsers.TBL_ROLES_USERS);
    }

    /**
     * Create a detached, initialised TblRolesUsersRecord
     */
    public TblRolesUsersRecord(Integer idUser, Integer idRole) {
        super(TblRolesUsers.TBL_ROLES_USERS);

        set(0, idUser);
        set(1, idRole);
    }
}
