/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblRecibosCompra;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosCompraRecord extends UpdatableRecordImpl<TblRecibosCompraRecord> implements Record8<Integer, String, Timestamp, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = -1686062893;

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.NRO</code>.
     */
    public void setNro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.NRO</code>.
     */
    public String getNro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.RAZON_SOCIAL</code>.
     */
    public void setRazonSocial(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.RAZON_SOCIAL</code>.
     */
    public String getRazonSocial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.RUC</code>.
     */
    public void setRuc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.RUC</code>.
     */
    public String getRuc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.OBSERVACION</code>.
     */
    public void setObservacion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.OBSERVACION</code>.
     */
    public String getObservacion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS_COMPRA.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS_COMPRA.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, String, String, Integer, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Timestamp, String, String, Integer, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.NRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.RAZON_SOCIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.RUC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.OBSERVACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblRecibosCompra.TBL_RECIBOS_COMPRA.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRuc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value2(String value) {
        setNro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value3(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value4(String value) {
        setRazonSocial(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value5(String value) {
        setRuc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value6(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value7(String value) {
        setObservacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord value8(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosCompraRecord values(Integer value1, String value2, Timestamp value3, String value4, String value5, Integer value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblRecibosCompraRecord
     */
    public TblRecibosCompraRecord() {
        super(TblRecibosCompra.TBL_RECIBOS_COMPRA);
    }

    /**
     * Create a detached, initialised TblRecibosCompraRecord
     */
    public TblRecibosCompraRecord(Integer id, String nro, Timestamp fechahora, String razonSocial, String ruc, Integer monto, String observacion, Integer idUser) {
        super(TblRecibosCompra.TBL_RECIBOS_COMPRA);

        set(0, id);
        set(1, nro);
        set(2, fechahora);
        set(3, razonSocial);
        set(4, ruc);
        set(5, monto);
        set(6, observacion);
        set(7, idUser);
    }
}
