/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblRecibos;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblRecibosRecord extends UpdatableRecordImpl<TblRecibosRecord> implements Record10<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -2086171075;

    /**
     * Setter for <code>MG.TBL_RECIBOS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.CONCEPTO</code>.
     */
    public void setConcepto(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.CONCEPTO</code>.
     */
    public String getConcepto() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.MONTO_APORTE</code>.
     */
    public void setMontoAporte(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.MONTO_APORTE</code>.
     */
    public Integer getMontoAporte() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.MONTO_DONACION</code>.
     */
    public void setMontoDonacion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.MONTO_DONACION</code>.
     */
    public Integer getMontoDonacion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.ID_ENTIDAD</code>.
     */
    public void setIdEntidad(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.ID_ENTIDAD</code>.
     */
    public Integer getIdEntidad() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.ID_EVENTO_TIPO</code>.
     */
    public void setIdEventoTipo(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.ID_EVENTO_TIPO</code>.
     */
    public Integer getIdEventoTipo() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.ID_EVENTO</code>.
     */
    public void setIdEvento(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.ID_EVENTO</code>.
     */
    public Integer getIdEvento() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>MG.TBL_RECIBOS.FECHAHORA_COMPROMISO</code>.
     */
    public void setFechahoraCompromiso(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TBL_RECIBOS.FECHAHORA_COMPROMISO</code>.
     */
    public Timestamp getFechahoraCompromiso() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Timestamp, String, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblRecibos.TBL_RECIBOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblRecibos.TBL_RECIBOS.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TblRecibos.TBL_RECIBOS.CONCEPTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblRecibos.TBL_RECIBOS.MONTO_APORTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblRecibos.TBL_RECIBOS.MONTO_DONACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TblRecibos.TBL_RECIBOS.ID_ENTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblRecibos.TBL_RECIBOS.ID_EVENTO_TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TblRecibos.TBL_RECIBOS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TblRecibos.TBL_RECIBOS.ID_EVENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TblRecibos.TBL_RECIBOS.FECHAHORA_COMPROMISO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMontoAporte();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMontoDonacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getIdEntidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdEventoTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIdEvento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getFechahoraCompromiso();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value3(String value) {
        setConcepto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value4(Integer value) {
        setMontoAporte(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value5(Integer value) {
        setMontoDonacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value6(Integer value) {
        setIdEntidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value7(Integer value) {
        setIdEventoTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value8(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value9(Integer value) {
        setIdEvento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord value10(Timestamp value) {
        setFechahoraCompromiso(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblRecibosRecord values(Integer value1, Timestamp value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblRecibosRecord
     */
    public TblRecibosRecord() {
        super(TblRecibos.TBL_RECIBOS);
    }

    /**
     * Create a detached, initialised TblRecibosRecord
     */
    public TblRecibosRecord(Integer id, Timestamp fechahora, String concepto, Integer montoAporte, Integer montoDonacion, Integer idEntidad, Integer idEventoTipo, Integer idUser, Integer idEvento, Timestamp fechahoraCompromiso) {
        super(TblRecibos.TBL_RECIBOS);

        set(0, id);
        set(1, fechahora);
        set(2, concepto);
        set(3, montoAporte);
        set(4, montoDonacion);
        set(5, idEntidad);
        set(6, idEventoTipo);
        set(7, idUser);
        set(8, idEvento);
        set(9, fechahoraCompromiso);
    }
}
