/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblTransferenciasAsientosTemporales;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTransferenciasAsientosTemporalesRecord extends TableRecordImpl<TblTransferenciasAsientosTemporalesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -326654874;

    /**
     * Setter for <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_TRANSFERENCIA</code>.
     */
    public void setIdTransferencia(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_TRANSFERENCIA</code>.
     */
    public Integer getIdTransferencia() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_ASIENTO_TEMPORAL</code>.
     */
    public void setIdAsientoTemporal(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_ASIENTO_TEMPORAL</code>.
     */
    public Integer getIdAsientoTemporal() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblTransferenciasAsientosTemporales.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_TRANSFERENCIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TblTransferenciasAsientosTemporales.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES.ID_ASIENTO_TEMPORAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdTransferencia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdAsientoTemporal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTransferenciasAsientosTemporalesRecord value1(Integer value) {
        setIdTransferencia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTransferenciasAsientosTemporalesRecord value2(Integer value) {
        setIdAsientoTemporal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTransferenciasAsientosTemporalesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblTransferenciasAsientosTemporalesRecord
     */
    public TblTransferenciasAsientosTemporalesRecord() {
        super(TblTransferenciasAsientosTemporales.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES);
    }

    /**
     * Create a detached, initialised TblTransferenciasAsientosTemporalesRecord
     */
    public TblTransferenciasAsientosTemporalesRecord(Integer idTransferencia, Integer idAsientoTemporal) {
        super(TblTransferenciasAsientosTemporales.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES);

        set(0, idTransferencia);
        set(1, idAsientoTemporal);
    }
}
