/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.TblTimbrados;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblTimbradosRecord extends UpdatableRecordImpl<TblTimbradosRecord> implements Record7<Integer, Timestamp, Timestamp, Integer, Integer, Boolean, Integer> {

    private static final long serialVersionUID = -757803139;

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.NRO</code>.
     */
    public void setNro(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.NRO</code>.
     */
    public Integer getNro() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.FECHA_INICIO</code>.
     */
    public void setFechaInicio(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.FECHA_INICIO</code>.
     */
    public Timestamp getFechaInicio() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.FECHA_VENCIMIENTO</code>.
     */
    public void setFechaVencimiento(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.FECHA_VENCIMIENTO</code>.
     */
    public Timestamp getFechaVencimiento() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.NRO_FACTURA_INCIO</code>.
     */
    public void setNroFacturaIncio(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.NRO_FACTURA_INCIO</code>.
     */
    public Integer getNroFacturaIncio() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.NRO_FACTURA_FIN</code>.
     */
    public void setNroFacturaFin(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.NRO_FACTURA_FIN</code>.
     */
    public Integer getNroFacturaFin() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.ACTIVO</code>.
     */
    public void setActivo(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.ACTIVO</code>.
     */
    public Boolean getActivo() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>MG.TBL_TIMBRADOS.ID_USER</code>.
     */
    public void setIdUser(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TBL_TIMBRADOS.ID_USER</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Timestamp, Integer, Integer, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Timestamp, Timestamp, Integer, Integer, Boolean, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblTimbrados.TBL_TIMBRADOS.NRO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TblTimbrados.TBL_TIMBRADOS.FECHA_INICIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TblTimbrados.TBL_TIMBRADOS.FECHA_VENCIMIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TblTimbrados.TBL_TIMBRADOS.NRO_FACTURA_INCIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TblTimbrados.TBL_TIMBRADOS.NRO_FACTURA_FIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return TblTimbrados.TBL_TIMBRADOS.ACTIVO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TblTimbrados.TBL_TIMBRADOS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getNro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFechaVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNroFacturaIncio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNroFacturaFin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getActivo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value1(Integer value) {
        setNro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value2(Timestamp value) {
        setFechaInicio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value3(Timestamp value) {
        setFechaVencimiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value4(Integer value) {
        setNroFacturaIncio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value5(Integer value) {
        setNroFacturaFin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value6(Boolean value) {
        setActivo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord value7(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblTimbradosRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4, Integer value5, Boolean value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblTimbradosRecord
     */
    public TblTimbradosRecord() {
        super(TblTimbrados.TBL_TIMBRADOS);
    }

    /**
     * Create a detached, initialised TblTimbradosRecord
     */
    public TblTimbradosRecord(Integer nro, Timestamp fechaInicio, Timestamp fechaVencimiento, Integer nroFacturaIncio, Integer nroFacturaFin, Boolean activo, Integer idUser) {
        super(TblTimbrados.TBL_TIMBRADOS);

        set(0, nro);
        set(1, fechaInicio);
        set(2, fechaVencimiento);
        set(3, nroFacturaIncio);
        set(4, nroFacturaFin);
        set(5, activo);
        set(6, idUser);
    }
}
