/*
 * This file is generated by jOOQ.
*/
package com.gnadenheimer.mg3.domain.jooq.tables.records;


import com.gnadenheimer.mg3.domain.jooq.tables.Transferencia;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransferenciaRecord extends TableRecordImpl<TransferenciaRecord> implements Record12<Integer, Timestamp, Integer, Integer, String, String, String, String, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1364792235;

    /**
     * Setter for <code>MG.TRANSFERENCIA.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.FECHAHORA</code>.
     */
    public void setFechahora(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.FECHAHORA</code>.
     */
    public Timestamp getFechahora() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.CTA_DEBITO</code>.
     */
    public void setCtaDebito(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.CTA_DEBITO</code>.
     */
    public Integer getCtaDebito() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.CTA_CREDITO</code>.
     */
    public void setCtaCredito(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.CTA_CREDITO</code>.
     */
    public Integer getCtaCredito() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.D_NOMBRE</code>.
     */
    public void setDNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.D_NOMBRE</code>.
     */
    public String getDNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.C_NOMBRE</code>.
     */
    public void setCNombre(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.C_NOMBRE</code>.
     */
    public String getCNombre() {
        return (String) get(5);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.D_DOMICILIO</code>.
     */
    public void setDDomicilio(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.D_DOMICILIO</code>.
     */
    public String getDDomicilio() {
        return (String) get(6);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.C_DOMICILIO</code>.
     */
    public void setCDomicilio(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.C_DOMICILIO</code>.
     */
    public String getCDomicilio() {
        return (String) get(7);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.D_BOX</code>.
     */
    public void setDBox(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.D_BOX</code>.
     */
    public Integer getDBox() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.C_BOX</code>.
     */
    public void setCBox(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.C_BOX</code>.
     */
    public Integer getCBox() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.MONTO</code>.
     */
    public void setMonto(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.MONTO</code>.
     */
    public Integer getMonto() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>MG.TRANSFERENCIA.CONCEPTO</code>.
     */
    public void setConcepto(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>MG.TRANSFERENCIA.CONCEPTO</code>.
     */
    public String getConcepto() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Timestamp, Integer, Integer, String, String, String, String, Integer, Integer, Integer, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Timestamp, Integer, Integer, String, String, String, String, Integer, Integer, Integer, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Transferencia.TRANSFERENCIA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Transferencia.TRANSFERENCIA.FECHAHORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Transferencia.TRANSFERENCIA.CTA_DEBITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Transferencia.TRANSFERENCIA.CTA_CREDITO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Transferencia.TRANSFERENCIA.D_NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Transferencia.TRANSFERENCIA.C_NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Transferencia.TRANSFERENCIA.D_DOMICILIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Transferencia.TRANSFERENCIA.C_DOMICILIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Transferencia.TRANSFERENCIA.D_BOX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Transferencia.TRANSFERENCIA.C_BOX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Transferencia.TRANSFERENCIA.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Transferencia.TRANSFERENCIA.CONCEPTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFechahora();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCtaDebito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCtaCredito();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getDBox();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCBox();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value2(Timestamp value) {
        setFechahora(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value3(Integer value) {
        setCtaDebito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value4(Integer value) {
        setCtaCredito(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value5(String value) {
        setDNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value6(String value) {
        setCNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value7(String value) {
        setDDomicilio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value8(String value) {
        setCDomicilio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value9(Integer value) {
        setDBox(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value10(Integer value) {
        setCBox(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value11(Integer value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord value12(String value) {
        setConcepto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransferenciaRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, Integer value9, Integer value10, Integer value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransferenciaRecord
     */
    public TransferenciaRecord() {
        super(Transferencia.TRANSFERENCIA);
    }

    /**
     * Create a detached, initialised TransferenciaRecord
     */
    public TransferenciaRecord(Integer id, Timestamp fechahora, Integer ctaDebito, Integer ctaCredito, String dNombre, String cNombre, String dDomicilio, String cDomicilio, Integer dBox, Integer cBox, Integer monto, String concepto) {
        super(Transferencia.TRANSFERENCIA);

        set(0, id);
        set(1, fechahora);
        set(2, ctaDebito);
        set(3, ctaCredito);
        set(4, dNombre);
        set(5, cNombre);
        set(6, dDomicilio);
        set(7, cDomicilio);
        set(8, dBox);
        set(9, cBox);
        set(10, monto);
        set(11, concepto);
    }
}
